DELETE FROM SC_WL_USUGRU;

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'tothom'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'STR_ADMIN'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'gestor', 'tothom'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'gestor', 'STR_GESTOR'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'registro', 'tothom'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'registro', 'RWE_USUARI'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'helpdesk', 'tothom'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'helpdesk', 'STR_HELPDESK'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'auto', 'STR_AUTO'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'demo', 'tothom'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'nobody', 'tothom'); 

INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_NOM, USU_NIF) 
VALUES ( 'delega', 'delega' , 'Administrador representaciones' ,null );

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'delega', 'STR_DELEGA');

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'delega', 'tothom'); 

-- From 1.1.4 to 1.1.5

INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_NOM, USU_NIF) 
VALUES ( 'nobody', 'nobody' , 'Usuari No Autenticat' , '00000000T' );