package es.caib.regtel.ws.v2.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Sun Feb 05 16:28:13 CET 2017
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:regtel:ws:v2:services", name = "BackofficeFacade")
@XmlSeeAlso({es.caib.regtel.ws.v2.model.ObjectFactory.class})
public interface BackofficeFacade {

    @WebResult(name = "obtenerDetalleAcuseReciboReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerDetalleAcuseRecibo", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.ObtenerDetalleAcuseRecibo")
    @WebMethod
    @ResponseWrapper(localName = "obtenerDetalleAcuseReciboResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.ObtenerDetalleAcuseReciboResponse")
    public es.caib.regtel.ws.v2.model.DetalleAcuseRecibo obtenerDetalleAcuseRecibo(
        @WebParam(name = "entidad", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistro", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        java.lang.String numeroRegistro
    ) throws BackofficeFacadeException;

    @WebResult(name = "registroEntradaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroEntrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.RegistroEntrada")
    @WebMethod
    @ResponseWrapper(localName = "registroEntradaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.RegistroEntradaResponse")
    public es.caib.regtel.ws.v2.model.ResultadoRegistro registroEntrada(
        @WebParam(name = "entrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        es.caib.regtel.ws.v2.model.DatosRegistroEntrada entrada
    ) throws BackofficeFacadeException;

    @WebResult(name = "prepararRegistroEntradaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "prepararRegistroEntrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.PrepararRegistroEntrada")
    @WebMethod
    @ResponseWrapper(localName = "prepararRegistroEntradaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.PrepararRegistroEntradaResponse")
    public es.caib.regtel.ws.v2.model.ReferenciaRDSAsientoRegistral prepararRegistroEntrada(
        @WebParam(name = "entrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        es.caib.regtel.ws.v2.model.DatosRegistroEntrada entrada,
        @WebParam(name = "diasPersistencia", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        java.lang.String diasPersistencia
    ) throws BackofficeFacadeException;

    @WebResult(name = "registroSalidaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroSalida", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.RegistroSalida")
    @WebMethod
    @ResponseWrapper(localName = "registroSalidaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.RegistroSalidaResponse")
    public es.caib.regtel.ws.v2.model.ResultadoRegistro registroSalida(
        @WebParam(name = "notificacion", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        es.caib.regtel.ws.v2.model.DatosRegistroSalida notificacion
    ) throws BackofficeFacadeException;

    @WebResult(name = "registroEntradaConFirmaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroEntradaConFirma", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.RegistroEntradaConFirma")
    @WebMethod
    @ResponseWrapper(localName = "registroEntradaConFirmaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.RegistroEntradaConFirmaResponse")
    public es.caib.regtel.ws.v2.model.ResultadoRegistro registroEntradaConFirma(
        @WebParam(name = "referenciaRDS", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        es.caib.regtel.ws.v2.model.ReferenciaRDSAsientoRegistral referenciaRDS,
        @WebParam(name = "firma", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        es.caib.regtel.ws.v2.model.FirmaWS firma
    ) throws BackofficeFacadeException;

    @WebResult(name = "obtenerAcuseReciboReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerAcuseRecibo", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.ObtenerAcuseRecibo")
    @WebMethod
    @ResponseWrapper(localName = "obtenerAcuseReciboResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.ObtenerAcuseReciboResponse")
    public es.caib.regtel.ws.v2.model.AcuseRecibo obtenerAcuseRecibo(
        @WebParam(name = "entidad", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistro", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        java.lang.String numeroRegistro
    ) throws BackofficeFacadeException;
}
