//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 04:41:18 PM CET 
//


package es.caib.xml.avisonotificacion.modelo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caib.xml.avisonotificacion.modelo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ACUSERECIBO_QNAME = new QName("", "ACUSE_RECIBO");
    private final static QName _UNIDADADMINISTRATIVA_QNAME = new QName("", "UNIDAD_ADMINISTRATIVA");
    private final static QName _IDENTIFICADOREXPEDIENTE_QNAME = new QName("", "IDENTIFICADOR_EXPEDIENTE");
    private final static QName _TEXTOSMS_QNAME = new QName("", "TEXTO_SMS");
    private final static QName _TITULO_QNAME = new QName("", "TITULO");
    private final static QName _TEXTO_QNAME = new QName("", "TEXTO");
    private final static QName _ACCESIBLEPORCLAVE_QNAME = new QName("", "ACCESIBLE_POR_CLAVE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.xml.avisonotificacion.modelo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EXPEDIENTE }
     * 
     */
    public EXPEDIENTE createEXPEDIENTE() {
        return new EXPEDIENTE();
    }

    /**
     * Create an instance of {@link AVISONOTIFICACION }
     * 
     */
    public AVISONOTIFICACION createAVISONOTIFICACION() {
        return new AVISONOTIFICACION();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACUSE_RECIBO")
    public JAXBElement<String> createACUSERECIBO(String value) {
        return new JAXBElement<String>(_ACUSERECIBO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UNIDAD_ADMINISTRATIVA")
    public JAXBElement<String> createUNIDADADMINISTRATIVA(String value) {
        return new JAXBElement<String>(_UNIDADADMINISTRATIVA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IDENTIFICADOR_EXPEDIENTE")
    public JAXBElement<String> createIDENTIFICADOREXPEDIENTE(String value) {
        return new JAXBElement<String>(_IDENTIFICADOREXPEDIENTE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXTO_SMS")
    public JAXBElement<String> createTEXTOSMS(String value) {
        return new JAXBElement<String>(_TEXTOSMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TITULO")
    public JAXBElement<String> createTITULO(String value) {
        return new JAXBElement<String>(_TITULO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXTO")
    public JAXBElement<String> createTEXTO(String value) {
        return new JAXBElement<String>(_TEXTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACCESIBLE_POR_CLAVE")
    public JAXBElement<String> createACCESIBLEPORCLAVE(String value) {
        return new JAXBElement<String>(_ACCESIBLEPORCLAVE_QNAME, String.class, null, value);
    }

}
