 ALTER TABLE RDS_MODELO  ADD MOD_CUSTOD           VARCHAR2(1)                    default 'N' not null;

comment on column RDS_MODELO.MOD_CUSTOD is
'INDICA SI SE DEBE CUSTODIAR EL DOCUMENTO FIRMADO';


create table RDS_VERCUS  (
   CUS_CODIGO           VARCHAR2(100)                   not null,
   CUS_CODDOC           NUMBER(20)                      not null,
   CUS_FECHA            DATE                            not null,
   CUS_BORRAR           VARCHAR2(1)                     not null
);

comment on table RDS_VERCUS is
'VERSIONES DE LA CUSTODIA DE UN DOCUMENTO FIRMADO';

comment on column RDS_VERCUS.CUS_CODIGO is
'CODIGO DEL DOCUMENTO EN LA CUSTODIA ';

comment on column RDS_VERCUS.CUS_CODDOC is
'CODIGO DEL DOCUMENTO';

comment on column RDS_VERCUS.CUS_FECHA is
'FECHA EN LA QUE SE REALIZA LA CUSTODIA';

comment on column RDS_VERCUS.CUS_BORRAR is
'INDICA SI EL DOCUMENTO DEBE SER BORRADO DE CUSTODIA (S/N)';

alter table RDS_VERCUS
   add constraint RDS_CUS_PK primary key (CUS_CODIGO);

alter table RDS_VERCUS
   add constraint RDS_CUSDOC_FK foreign key (CUS_CODDOC)
      references RDS_DOCUM (DOC_CODIGO);
      
INSERT INTO RDS_MODELO (MOD_CODIGO, MOD_MODELO, MOD_NOMBRE,MOD_DESC, MOD_ESTRUC) 
VALUES ( RDS_SEQMOD.NEXTVAL, 'GE0011NOTIFICA', 'DOCUMENTO DE NOTIFICACION', 'DOCUMENTO ASOCIADO A UN REGISTRO DE SALIDA' , 'N');      

INSERT INTO RDS_VERS ( VER_CODIGO, VER_CODMOD, VER_VERSIO, VER_DESC) 
VALUES (RDS_SEQVER.NEXTVAL , (SELECT MOD_CODIGO FROM RDS_MODELO WHERE MOD_MODELO='GE0011NOTIFICA'),1,'NOTIFICACION');

COMMIT;
      
