-- Actualizacion vista para contemplar estado de solicitud enviada pendiente de entregar doc presencial (preregistros)
CREATE OR REPLACE VIEW ZPE_ESTEXP
(EST_ID, EST_TIPO, EST_CODIGO, EST_DESC, EST_FECINI, 
 EST_FECFIN, EST_ESTADO, EST_AUTENT, EST_USER, EST_NIFRDO, 
 EST_IDIOMA, EST_CODEXP, EST_UNIADM)
AS 
(
SELECT 'T' ||TO_CHAR(ENT_CODIGO), 'T',ENT_CODIGO,ENT_DESC,ENT_FECHA,ENT_FECHA,'SE', DECODE(ENT_NIVAUT,'A','N','S'), 
DECODE(ENT_NIVAUT,'A',ENT_IDEPER,ENT_USER), ENT_NIFRDO,ENT_IDIOMA,NULL,NULL
FROM ZPE_ENTTEL
WHERE 
ENT_CODIGO NOT IN 
(
 SELECT ELE_CODELE FROM ZPE_ELEEX WHERE ELE_TIPO = 'T'
)

UNION

SELECT  'P' ||TO_CHAR(PRE_CODIGO),'P',PRE_CODIGO,PRE_DESC,PRE_FECHA,PRE_FECHA, NVL2(PRE_FECREG,'SE','SP'),DECODE(PRE_NIVAUT,'A','N','S'),  
DECODE(PRE_NIVAUT,'A',PRE_IDEPER,PRE_USER), PRE_NIFRDO,PRE_IDIOMA,NULL,NULL
FROM ZPE_PREREG
WHERE 
PRE_CODIGO NOT IN 
(
 SELECT ELE_CODELE FROM ZPE_ELEEX WHERE ELE_TIPO = 'P'
)

UNION

SELECT  'E' ||TO_CHAR(EXP_CODIGO),'E',EXP_CODIGO,EXP_DESC,EXP_FECINI,EXP_FECULT,EXP_ESTADO,'S',EXP_SEYCIU, EXP_NIFRDO,EXP_IDIOMA,EXP_IDEXP,EXP_UNIADM
FROM ZPE_EXPEDI
WHERE EXP_SEYCIU IS NOT NULL

UNION

SELECT 'E' ||TO_CHAR(EXP_CODIGO),'E',EXP_CODIGO,EXP_DESC,EXP_FECINI,EXP_FECULT,EXP_ESTADO,'N',ENT_IDEPER, EXP_NIFRDO,EXP_IDIOMA,EXP_IDEXP,EXP_UNIADM
FROM ZPE_EXPEDI,ZPE_ELEEX,ZPE_ENTTEL
WHERE EXP_SEYCIU IS NULL AND
	  EXP_CODIGO = ELE_CODEXP AND
	  ELE_TIPO = 'T' AND ELE_CODELE = ENT_CODIGO
      
UNION
	  
SELECT 'E' ||TO_CHAR(EXP_CODIGO),'E',EXP_CODIGO,EXP_DESC,EXP_FECINI,EXP_FECULT,EXP_ESTADO,'N',PRE_IDEPER, EXP_NIFRDO,EXP_IDIOMA,EXP_IDEXP,EXP_UNIADM
FROM ZPE_EXPEDI,ZPE_ELEEX,ZPE_PREREG
WHERE EXP_SEYCIU IS NULL AND
	  EXP_CODIGO = ELE_CODEXP AND
	  ELE_TIPO = 'P' AND ELE_CODELE = PRE_CODIGO      	  
);


--- Actualizacion tabla pagos CAIB

alter table ZPE_RPAGOS add PAG_IDETRA VARCHAR2(50);
alter table ZPE_RPAGOS add PAG_MODTRA VARCHAR2(10);
alter table ZPE_RPAGOS add PAG_VERTRA NUMBER(2);
alter table ZPE_RPAGOS modify PAG_NIFDEC VARCHAR2(12);

comment on column ZPE_RPAGOS.PAG_IDETRA is
'Identificador del trámite (Id persistencia)';

comment on column ZPE_RPAGOS.PAG_MODTRA is
'Modelo del trámite';

comment on column ZPE_RPAGOS.PAG_VERTRA is
'Versión del trámite';
