//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.07 at 08:58:59 AM CEST 
//


package es.caib.xml.taxa.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SIGLES" minOccurs="0"/>
 *         &lt;element ref="{}NOM_VIA" minOccurs="0"/>
 *         &lt;element ref="{}NUMERO" minOccurs="0"/>
 *         &lt;element ref="{}LLETRA" minOccurs="0"/>
 *         &lt;element ref="{}ESCALA" minOccurs="0"/>
 *         &lt;element ref="{}PIS" minOccurs="0"/>
 *         &lt;element ref="{}PORTA" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sigles",
    "nomvia",
    "numero",
    "lletra",
    "escala",
    "pis",
    "porta"
})
@XmlRootElement(name = "DOMICILI")
public class DOMICILI {

    @XmlElement(name = "SIGLES")
    protected SIGLES sigles;
    @XmlElement(name = "NOM_VIA")
    protected NOMVIA nomvia;
    @XmlElement(name = "NUMERO")
    protected NUMERO numero;
    @XmlElement(name = "LLETRA")
    protected LLETRA lletra;
    @XmlElement(name = "ESCALA")
    protected ESCALA escala;
    @XmlElement(name = "PIS")
    protected PIS pis;
    @XmlElement(name = "PORTA")
    protected PORTA porta;

    /**
     * Gets the value of the sigles property.
     * 
     * @return
     *     possible object is
     *     {@link SIGLES }
     *     
     */
    public SIGLES getSIGLES() {
        return sigles;
    }

    /**
     * Sets the value of the sigles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIGLES }
     *     
     */
    public void setSIGLES(SIGLES value) {
        this.sigles = value;
    }

    /**
     * Gets the value of the nomvia property.
     * 
     * @return
     *     possible object is
     *     {@link NOMVIA }
     *     
     */
    public NOMVIA getNOMVIA() {
        return nomvia;
    }

    /**
     * Sets the value of the nomvia property.
     * 
     * @param value
     *     allowed object is
     *     {@link NOMVIA }
     *     
     */
    public void setNOMVIA(NOMVIA value) {
        this.nomvia = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link NUMERO }
     *     
     */
    public NUMERO getNUMERO() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link NUMERO }
     *     
     */
    public void setNUMERO(NUMERO value) {
        this.numero = value;
    }

    /**
     * Gets the value of the lletra property.
     * 
     * @return
     *     possible object is
     *     {@link LLETRA }
     *     
     */
    public LLETRA getLLETRA() {
        return lletra;
    }

    /**
     * Sets the value of the lletra property.
     * 
     * @param value
     *     allowed object is
     *     {@link LLETRA }
     *     
     */
    public void setLLETRA(LLETRA value) {
        this.lletra = value;
    }

    /**
     * Gets the value of the escala property.
     * 
     * @return
     *     possible object is
     *     {@link ESCALA }
     *     
     */
    public ESCALA getESCALA() {
        return escala;
    }

    /**
     * Sets the value of the escala property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESCALA }
     *     
     */
    public void setESCALA(ESCALA value) {
        this.escala = value;
    }

    /**
     * Gets the value of the pis property.
     * 
     * @return
     *     possible object is
     *     {@link PIS }
     *     
     */
    public PIS getPIS() {
        return pis;
    }

    /**
     * Sets the value of the pis property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIS }
     *     
     */
    public void setPIS(PIS value) {
        this.pis = value;
    }

    /**
     * Gets the value of the porta property.
     * 
     * @return
     *     possible object is
     *     {@link PORTA }
     *     
     */
    public PORTA getPORTA() {
        return porta;
    }

    /**
     * Sets the value of the porta property.
     * 
     * @param value
     *     allowed object is
     *     {@link PORTA }
     *     
     */
    public void setPORTA(PORTA value) {
        this.porta = value;
    }

}
