//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.07 at 08:58:59 AM CEST 
//


package es.caib.xml.taxa.modelo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caib.xml.taxa.modelo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MODELO_QNAME = new QName("", "MODELO");
    private final static QName _LOCALIZADOR_QNAME = new QName("", "LOCALIZADOR");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.xml.taxa.modelo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IDTAXA }
     * 
     */
    public IDTAXA createIDTAXA() {
        return new IDTAXA();
    }

    /**
     * Create an instance of {@link NUMERO }
     * 
     */
    public NUMERO createNUMERO() {
        return new NUMERO();
    }

    /**
     * Create an instance of {@link CONCEPTE }
     * 
     */
    public CONCEPTE createCONCEPTE() {
        return new CONCEPTE();
    }

    /**
     * Create an instance of {@link PIS }
     * 
     */
    public PIS createPIS() {
        return new PIS();
    }

    /**
     * Create an instance of {@link ESCALA }
     * 
     */
    public ESCALA createESCALA() {
        return new ESCALA();
    }

    /**
     * Create an instance of {@link LOCALITAT }
     * 
     */
    public LOCALITAT createLOCALITAT() {
        return new LOCALITAT();
    }

    /**
     * Create an instance of {@link DECLARANT }
     * 
     */
    public DECLARANT createDECLARANT() {
        return new DECLARANT();
    }

    /**
     * Create an instance of {@link DOMICILI }
     * 
     */
    public DOMICILI createDOMICILI() {
        return new DOMICILI();
    }

    /**
     * Create an instance of {@link SUBCONCEPTE }
     * 
     */
    public SUBCONCEPTE createSUBCONCEPTE() {
        return new SUBCONCEPTE();
    }

    /**
     * Create an instance of {@link IMPORT }
     * 
     */
    public IMPORT createIMPORT() {
        return new IMPORT();
    }

    /**
     * Create an instance of {@link PROVINCIA }
     * 
     */
    public PROVINCIA createPROVINCIA() {
        return new PROVINCIA();
    }

    /**
     * Create an instance of {@link PORTA }
     * 
     */
    public PORTA createPORTA() {
        return new PORTA();
    }

    /**
     * Create an instance of {@link CODIPOSTAL }
     * 
     */
    public CODIPOSTAL createCODIPOSTAL() {
        return new CODIPOSTAL();
    }

    /**
     * Create an instance of {@link LLETRA }
     * 
     */
    public LLETRA createLLETRA() {
        return new LLETRA();
    }

    /**
     * Create an instance of {@link SIGLES }
     * 
     */
    public SIGLES createSIGLES() {
        return new SIGLES();
    }

    /**
     * Create an instance of {@link FAX }
     * 
     */
    public FAX createFAX() {
        return new FAX();
    }

    /**
     * Create an instance of {@link TELEFON }
     * 
     */
    public TELEFON createTELEFON() {
        return new TELEFON();
    }

    /**
     * Create an instance of {@link NOM }
     * 
     */
    public NOM createNOM() {
        return new NOM();
    }

    /**
     * Create an instance of {@link NOMVIA }
     * 
     */
    public NOMVIA createNOMVIA() {
        return new NOMVIA();
    }

    /**
     * Create an instance of {@link NIF }
     * 
     */
    public NIF createNIF() {
        return new NIF();
    }

    /**
     * Create an instance of {@link TAXA }
     * 
     */
    public TAXA createTAXA() {
        return new TAXA();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MODELO")
    public JAXBElement<String> createMODELO(String value) {
        return new JAXBElement<String>(_MODELO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LOCALIZADOR")
    public JAXBElement<String> createLOCALIZADOR(String value) {
        return new JAXBElement<String>(_LOCALIZADOR_QNAME, String.class, null, value);
    }

}
