//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 10:40:52 AM CEST 
//


package es.caib.xml.registro.modelo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DATOS_ORIGEN"/>
 *         &lt;element ref="{}DATOS_DESTINO" minOccurs="0"/>
 *         &lt;element ref="{}DATOS_INTERESADO" maxOccurs="unbounded"/>
 *         &lt;element ref="{}DATOS_ASUNTO"/>
 *         &lt;element ref="{}DATOS_ANEXO_DOCUMENTACION" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosorigen",
    "datosdestino",
    "datosinteresado",
    "datosasunto",
    "datosanexodocumentacion"
})
@XmlRootElement(name = "ASIENTO_REGISTRAL")
public class ASIENTOREGISTRAL {

    @XmlElement(name = "DATOS_ORIGEN", required = true)
    protected DATOSORIGEN datosorigen;
    @XmlElement(name = "DATOS_DESTINO")
    protected DATOSDESTINO datosdestino;
    @XmlElement(name = "DATOS_INTERESADO", required = true)
    protected List<DATOSINTERESADO> datosinteresado;
    @XmlElement(name = "DATOS_ASUNTO", required = true)
    protected DATOSASUNTO datosasunto;
    @XmlElement(name = "DATOS_ANEXO_DOCUMENTACION", required = true)
    protected List<DATOSANEXODOCUMENTACION> datosanexodocumentacion;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String version;

    /**
     * Gets the value of the datosorigen property.
     * 
     * @return
     *     possible object is
     *     {@link DATOSORIGEN }
     *     
     */
    public DATOSORIGEN getDATOSORIGEN() {
        return datosorigen;
    }

    /**
     * Sets the value of the datosorigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATOSORIGEN }
     *     
     */
    public void setDATOSORIGEN(DATOSORIGEN value) {
        this.datosorigen = value;
    }

    /**
     * Gets the value of the datosdestino property.
     * 
     * @return
     *     possible object is
     *     {@link DATOSDESTINO }
     *     
     */
    public DATOSDESTINO getDATOSDESTINO() {
        return datosdestino;
    }

    /**
     * Sets the value of the datosdestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATOSDESTINO }
     *     
     */
    public void setDATOSDESTINO(DATOSDESTINO value) {
        this.datosdestino = value;
    }

    /**
     * Gets the value of the datosinteresado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datosinteresado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATOSINTERESADO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DATOSINTERESADO }
     * 
     * 
     */
    public List<DATOSINTERESADO> getDATOSINTERESADO() {
        if (datosinteresado == null) {
            datosinteresado = new ArrayList<DATOSINTERESADO>();
        }
        return this.datosinteresado;
    }

    /**
     * Gets the value of the datosasunto property.
     * 
     * @return
     *     possible object is
     *     {@link DATOSASUNTO }
     *     
     */
    public DATOSASUNTO getDATOSASUNTO() {
        return datosasunto;
    }

    /**
     * Sets the value of the datosasunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATOSASUNTO }
     *     
     */
    public void setDATOSASUNTO(DATOSASUNTO value) {
        this.datosasunto = value;
    }

    /**
     * Gets the value of the datosanexodocumentacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datosanexodocumentacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATOSANEXODOCUMENTACION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DATOSANEXODOCUMENTACION }
     * 
     * 
     */
    public List<DATOSANEXODOCUMENTACION> getDATOSANEXODOCUMENTACION() {
        if (datosanexodocumentacion == null) {
            datosanexodocumentacion = new ArrayList<DATOSANEXODOCUMENTACION>();
        }
        return this.datosanexodocumentacion;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
