//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 10:40:52 AM CEST 
//


package es.caib.xml.registro.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NIVEL_AUTENTICACION" minOccurs="0"/>
 *         &lt;element ref="{}USUARIO_SEYCON" minOccurs="0"/>
 *         &lt;element ref="{}TIPO_INTERESADO"/>
 *         &lt;element ref="{}TIPO_IDENTIFICACION" minOccurs="0"/>
 *         &lt;element ref="{}NUMERO_IDENTIFICACION" minOccurs="0"/>
 *         &lt;element ref="{}FORMATO_DATOS_INTERESADO"/>
 *         &lt;element ref="{}IDENTIFICACION_INTERESADO"/>
 *         &lt;element ref="{}IDENTIFICACION_INTERESADO_DESGLOSADA" minOccurs="0"/>
 *         &lt;element ref="{}DIRECCION_CODIFICADA" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nivelautenticacion",
    "usuarioseycon",
    "tipointeresado",
    "tipoidentificacion",
    "numeroidentificacion",
    "formatodatosinteresado",
    "identificacioninteresado",
    "identificacioninteresadodesglosada",
    "direccioncodificada"
})
@XmlRootElement(name = "DATOS_INTERESADO")
public class DATOSINTERESADO {

    @XmlElement(name = "NIVEL_AUTENTICACION")
    protected String nivelautenticacion;
    @XmlElement(name = "USUARIO_SEYCON")
    protected String usuarioseycon;
    @XmlElement(name = "TIPO_INTERESADO", required = true)
    protected String tipointeresado;
    @XmlElement(name = "TIPO_IDENTIFICACION")
    protected String tipoidentificacion;
    @XmlElement(name = "NUMERO_IDENTIFICACION")
    protected String numeroidentificacion;
    @XmlElement(name = "FORMATO_DATOS_INTERESADO", required = true)
    protected String formatodatosinteresado;
    @XmlElement(name = "IDENTIFICACION_INTERESADO", required = true)
    protected String identificacioninteresado;
    @XmlElement(name = "IDENTIFICACION_INTERESADO_DESGLOSADA")
    protected IDENTIFICACIONINTERESADODESGLOSADA identificacioninteresadodesglosada;
    @XmlElement(name = "DIRECCION_CODIFICADA")
    protected DIRECCIONCODIFICADA direccioncodificada;

    /**
     * Gets the value of the nivelautenticacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIVELAUTENTICACION() {
        return nivelautenticacion;
    }

    /**
     * Sets the value of the nivelautenticacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIVELAUTENTICACION(String value) {
        this.nivelautenticacion = value;
    }

    /**
     * Gets the value of the usuarioseycon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSUARIOSEYCON() {
        return usuarioseycon;
    }

    /**
     * Sets the value of the usuarioseycon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSUARIOSEYCON(String value) {
        this.usuarioseycon = value;
    }

    /**
     * Gets the value of the tipointeresado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOINTERESADO() {
        return tipointeresado;
    }

    /**
     * Sets the value of the tipointeresado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOINTERESADO(String value) {
        this.tipointeresado = value;
    }

    /**
     * Gets the value of the tipoidentificacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOIDENTIFICACION() {
        return tipoidentificacion;
    }

    /**
     * Sets the value of the tipoidentificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOIDENTIFICACION(String value) {
        this.tipoidentificacion = value;
    }

    /**
     * Gets the value of the numeroidentificacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMEROIDENTIFICACION() {
        return numeroidentificacion;
    }

    /**
     * Sets the value of the numeroidentificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMEROIDENTIFICACION(String value) {
        this.numeroidentificacion = value;
    }

    /**
     * Gets the value of the formatodatosinteresado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORMATODATOSINTERESADO() {
        return formatodatosinteresado;
    }

    /**
     * Sets the value of the formatodatosinteresado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORMATODATOSINTERESADO(String value) {
        this.formatodatosinteresado = value;
    }

    /**
     * Gets the value of the identificacioninteresado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDENTIFICACIONINTERESADO() {
        return identificacioninteresado;
    }

    /**
     * Sets the value of the identificacioninteresado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDENTIFICACIONINTERESADO(String value) {
        this.identificacioninteresado = value;
    }

    /**
     * Gets the value of the identificacioninteresadodesglosada property.
     * 
     * @return
     *     possible object is
     *     {@link IDENTIFICACIONINTERESADODESGLOSADA }
     *     
     */
    public IDENTIFICACIONINTERESADODESGLOSADA getIDENTIFICACIONINTERESADODESGLOSADA() {
        return identificacioninteresadodesglosada;
    }

    /**
     * Sets the value of the identificacioninteresadodesglosada property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDENTIFICACIONINTERESADODESGLOSADA }
     *     
     */
    public void setIDENTIFICACIONINTERESADODESGLOSADA(IDENTIFICACIONINTERESADODESGLOSADA value) {
        this.identificacioninteresadodesglosada = value;
    }

    /**
     * Gets the value of the direccioncodificada property.
     * 
     * @return
     *     possible object is
     *     {@link DIRECCIONCODIFICADA }
     *     
     */
    public DIRECCIONCODIFICADA getDIRECCIONCODIFICADA() {
        return direccioncodificada;
    }

    /**
     * Sets the value of the direccioncodificada property.
     * 
     * @param value
     *     allowed object is
     *     {@link DIRECCIONCODIFICADA }
     *     
     */
    public void setDIRECCIONCODIFICADA(DIRECCIONCODIFICADA value) {
        this.direccioncodificada = value;
    }

}
