//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 02:58:51 PM CEST 
//


package es.caib.xml.registro.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FECHA_ASUNTO" minOccurs="0"/>
 *         &lt;element ref="{}IDIOMA_ASUNTO"/>
 *         &lt;element ref="{}TIPO_ASUNTO"/>
 *         &lt;element ref="{}EXTRACTO_ASUNTO"/>
 *         &lt;element ref="{}CODIGO_ORGANO_DESTINO"/>
 *         &lt;element ref="{}DESCRIPCION_ORGANO_DESTINO" minOccurs="0"/>
 *         &lt;element ref="{}CODIGO_UNIDAD_ADMINISTRATIVA"/>
 *         &lt;element ref="{}IDENTIFICADOR_TRAMITE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fechaasunto",
    "idiomaasunto",
    "tipoasunto",
    "extractoasunto",
    "codigoorganodestino",
    "descripcionorganodestino",
    "codigounidadadministrativa",
    "identificadortramite"
})
@XmlRootElement(name = "DATOS_ASUNTO")
public class DATOSASUNTO {

    @XmlElement(name = "FECHA_ASUNTO")
    protected String fechaasunto;
    @XmlElement(name = "IDIOMA_ASUNTO", required = true)
    protected String idiomaasunto;
    @XmlElement(name = "TIPO_ASUNTO", required = true)
    protected String tipoasunto;
    @XmlElement(name = "EXTRACTO_ASUNTO", required = true)
    protected String extractoasunto;
    @XmlElement(name = "CODIGO_ORGANO_DESTINO", required = true)
    protected String codigoorganodestino;
    @XmlElement(name = "DESCRIPCION_ORGANO_DESTINO")
    protected String descripcionorganodestino;
    @XmlElement(name = "CODIGO_UNIDAD_ADMINISTRATIVA", required = true)
    protected String codigounidadadministrativa;
    @XmlElement(name = "IDENTIFICADOR_TRAMITE")
    protected String identificadortramite;

    /**
     * Gets the value of the fechaasunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHAASUNTO() {
        return fechaasunto;
    }

    /**
     * Sets the value of the fechaasunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHAASUNTO(String value) {
        this.fechaasunto = value;
    }

    /**
     * Gets the value of the idiomaasunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDIOMAASUNTO() {
        return idiomaasunto;
    }

    /**
     * Sets the value of the idiomaasunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDIOMAASUNTO(String value) {
        this.idiomaasunto = value;
    }

    /**
     * Gets the value of the tipoasunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOASUNTO() {
        return tipoasunto;
    }

    /**
     * Sets the value of the tipoasunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOASUNTO(String value) {
        this.tipoasunto = value;
    }

    /**
     * Gets the value of the extractoasunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTRACTOASUNTO() {
        return extractoasunto;
    }

    /**
     * Sets the value of the extractoasunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTRACTOASUNTO(String value) {
        this.extractoasunto = value;
    }

    /**
     * Gets the value of the codigoorganodestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIGOORGANODESTINO() {
        return codigoorganodestino;
    }

    /**
     * Sets the value of the codigoorganodestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIGOORGANODESTINO(String value) {
        this.codigoorganodestino = value;
    }

    /**
     * Gets the value of the descripcionorganodestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPCIONORGANODESTINO() {
        return descripcionorganodestino;
    }

    /**
     * Sets the value of the descripcionorganodestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPCIONORGANODESTINO(String value) {
        this.descripcionorganodestino = value;
    }

    /**
     * Gets the value of the codigounidadadministrativa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIGOUNIDADADMINISTRATIVA() {
        return codigounidadadministrativa;
    }

    /**
     * Sets the value of the codigounidadadministrativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIGOUNIDADADMINISTRATIVA(String value) {
        this.codigounidadadministrativa = value;
    }

    /**
     * Gets the value of the identificadortramite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDENTIFICADORTRAMITE() {
        return identificadortramite;
    }

    /**
     * Sets the value of the identificadortramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDENTIFICADORTRAMITE(String value) {
        this.identificadortramite = value;
    }

}
