//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 10:40:52 AM CEST 
//


package es.caib.xml.registro.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CODIGO_ENTIDAD_REGISTRAL_ORIGEN"/>
 *         &lt;element ref="{}NUMERO_REGISTRO"/>
 *         &lt;element ref="{}FECHA_ENTRADA_REGISTRO"/>
 *         &lt;element ref="{}TIPO_REGISTRO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoentidadregistralorigen",
    "numeroregistro",
    "fechaentradaregistro",
    "tiporegistro"
})
@XmlRootElement(name = "DATOS_ORIGEN")
public class DATOSORIGEN {

    @XmlElement(name = "CODIGO_ENTIDAD_REGISTRAL_ORIGEN", required = true)
    protected String codigoentidadregistralorigen;
    @XmlElement(name = "NUMERO_REGISTRO", required = true)
    protected String numeroregistro;
    @XmlElement(name = "FECHA_ENTRADA_REGISTRO", required = true)
    protected String fechaentradaregistro;
    @XmlElement(name = "TIPO_REGISTRO", required = true)
    protected String tiporegistro;

    /**
     * Gets the value of the codigoentidadregistralorigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIGOENTIDADREGISTRALORIGEN() {
        return codigoentidadregistralorigen;
    }

    /**
     * Sets the value of the codigoentidadregistralorigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIGOENTIDADREGISTRALORIGEN(String value) {
        this.codigoentidadregistralorigen = value;
    }

    /**
     * Gets the value of the numeroregistro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMEROREGISTRO() {
        return numeroregistro;
    }

    /**
     * Sets the value of the numeroregistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMEROREGISTRO(String value) {
        this.numeroregistro = value;
    }

    /**
     * Gets the value of the fechaentradaregistro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHAENTRADAREGISTRO() {
        return fechaentradaregistro;
    }

    /**
     * Sets the value of the fechaentradaregistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHAENTRADAREGISTRO(String value) {
        this.fechaentradaregistro = value;
    }

    /**
     * Gets the value of the tiporegistro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOREGISTRO() {
        return tiporegistro;
    }

    /**
     * Sets the value of the tiporegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOREGISTRO(String value) {
        this.tiporegistro = value;
    }

}
