//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.19 at 11:48:00 AM CET 
//


package es.caib.xml.datospropios.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EXPEDIENTE_CODIGO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPEDIENTE_UNIDAD_ADMINISTRATIVA" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "expedientecodigo",
    "expedienteunidadadministrativa"
})
@XmlRootElement(name = "TRAMITE_SUBSANACION")
public class TRAMITESUBSANACION {

    @XmlElement(name = "EXPEDIENTE_CODIGO", required = true)
    protected String expedientecodigo;
    @XmlElement(name = "EXPEDIENTE_UNIDAD_ADMINISTRATIVA")
    protected long expedienteunidadadministrativa;

    /**
     * Gets the value of the expedientecodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPEDIENTECODIGO() {
        return expedientecodigo;
    }

    /**
     * Sets the value of the expedientecodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPEDIENTECODIGO(String value) {
        this.expedientecodigo = value;
    }

    /**
     * Gets the value of the expedienteunidadadministrativa property.
     * 
     */
    public long getEXPEDIENTEUNIDADADMINISTRATIVA() {
        return expedienteunidadadministrativa;
    }

    /**
     * Sets the value of the expedienteunidadadministrativa property.
     * 
     */
    public void setEXPEDIENTEUNIDADADMINISTRATIVA(long value) {
        this.expedienteunidadadministrativa = value;
    }

}
