ALTER TABLE BTE_GESTOR
 ADD (GES_GESEXP  VARCHAR2(1)                  DEFAULT 'N'                   NOT NULL);


COMMENT ON COLUMN BTE_GESTOR.GES_GESEXP IS 'PERMITE GESTIONAR EXPEDIENTES';



CREATE INDEX BTE_TRA_BUSENT_I ON BTE_TRAMIT (TRA_IDETRA, TRA_PROCES, TRA_FECHA);