package es.caib.redose.model;
// Generated 07-mar-2006 18:19:34 by Hibernate Tools 3.1.0 beta3

/**
 * PlantillaIdioma generated by hbm2java
 */

public class PlantillaIdioma  implements java.io.Serializable, Traduccion {


    // Fields    
     private Long codigo;
     private Plantilla plantilla;
     private String idioma;
     private String nombreFichero;
     private ArchivoPlantilla archivo;


    // Constructors

    /** default constructor */
    public PlantillaIdioma() {
    }

       
    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long pliCodigo) {
        this.codigo = pliCodigo;
    }

    public Plantilla getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(Plantilla redosePlanti) {
        this.plantilla = redosePlanti;
    }

    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String redoseIdioma) {
        this.idioma = redoseIdioma;
    }


	public String getNombreFichero()
	{
		return nombreFichero;
	}


	public ArchivoPlantilla getArchivo()
	{
		return archivo;
	}


	public void setArchivo(ArchivoPlantilla archivo)
	{
		this.archivo = archivo;
	}


	public void setNombreFichero(String nombreFichero)
	{
		this.nombreFichero = nombreFichero;
	}
    
	public String toString()
	{
		StringBuffer sb = new StringBuffer();
		sb.append( "[Codigo: " ).append( this.getCodigo() ).append( "; Plantilla: " ).append( ( this.getPlantilla() != null ? this.getPlantilla().getCodigo() : ( Object ) "NO CODE" ) ).append( "; Idioma: ").append( this.getIdioma() ).append( "; Nombre fichero: " ).append( this.getNombreFichero ());
		/*
		if ( archivo != null )
		{
			sb.append( "; Archivo: " ).append( new String( archivo.getDatos() ));
		}
		*/
		sb.append( "]");
		return sb.toString();
	}
	
}
