CREATE TABLE SC_WL_USUARI
(
  USU_CODI    VARCHAR2(200 CHAR)                NOT NULL,
  USU_PASS    VARCHAR2(50 CHAR),
  USU_NOM     VARCHAR2(50 CHAR),
  USU_NIF     VARCHAR2(10 CHAR)
);

CREATE TABLE SC_WL_USUGRU
(
  UGR_CODUSU  VARCHAR2(200 CHAR),
  UGR_CODGRU  VARCHAR2(50 CHAR)
);

CREATE UNIQUE INDEX DNI_AK ON SC_WL_USUARI (USU_NIF);


CREATE UNIQUE INDEX USUARI_PK ON SC_WL_USUARI (USU_CODI);


ALTER TABLE SC_WL_USUARI ADD (CONSTRAINT USUARI_PK PRIMARY KEY (USU_CODI));
