package es.caib.sistra.model;
// Generated 21-mar-2006 11:41:40 by Hibernate Tools 3.1.0 beta3



/**
 * StrTradnv generated by hbm2java
 */

public class TraDocumentoNivel  implements Traduccion {


    // Fields    
     private String informacion;

	public String getInformacion() {
		return informacion;
	}

	public void setInformacion(String informacion) {
		this.informacion = informacion;
	}



}
