ALTER table MOB_MSEMAI  ADD  MSE_REMITE           VARCHAR(500);
ALTER table MOB_MSEMAI  ADD  MSE_REPLTO           VARCHAR(500);

comment on column MOB_MSEMAI.MSE_REMITE is
'TEXTO QUE APARECE COMO REMITENTE';

comment on column MOB_MSEMAI.MSE_REPLTO is
'EMAIL QUE APARECE COMO REPLY TO';