ALTER table BTE_PROAPL ADD  TAP_PLNOTV  VARCHAR(1) default 'N' not null;
comment on column BTE_PROAPL.TAP_PLNOTV is 'INDICA SI PERMITE PLAZO NOTIFICACIONES VARIABLE (S/N)';

ALTER table BTE_PROAPL ALTER COLUMN TAP_URL TYPE VARCHAR(500);