//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.05 at 03:49:14 PM CEST 
//


package es.caib.xml.delegacion.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ENTIDAD_ID" type="{}string_no_vacio"/>
 *         &lt;element name="ENTIDAD_NOMBRE" type="{}string_no_vacio"/>
 *         &lt;element name="DELEGADO_ID" type="{}string_no_vacio"/>
 *         &lt;element name="DELEGADO_NOMBRE" type="{}string_no_vacio"/>
 *         &lt;element name="PERMISOS" type="{}string_no_vacio"/>
 *         &lt;element name="FECHA_INICIO" type="{}string_fecha"/>
 *         &lt;element name="FECHA_FIN" type="{}string_fecha"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entidadid",
    "entidadnombre",
    "delegadoid",
    "delegadonombre",
    "permisos",
    "fechainicio",
    "fechafin"
})
@XmlRootElement(name = "AUTORIZACION_DELEGACION")
public class AUTORIZACIONDELEGACION {

    @XmlElement(name = "ENTIDAD_ID", required = true)
    protected String entidadid;
    @XmlElement(name = "ENTIDAD_NOMBRE", required = true)
    protected String entidadnombre;
    @XmlElement(name = "DELEGADO_ID", required = true)
    protected String delegadoid;
    @XmlElement(name = "DELEGADO_NOMBRE", required = true)
    protected String delegadonombre;
    @XmlElement(name = "PERMISOS", required = true)
    protected String permisos;
    @XmlElement(name = "FECHA_INICIO", required = true)
    protected String fechainicio;
    @XmlElement(name = "FECHA_FIN", required = true)
    protected String fechafin;

    /**
     * Gets the value of the entidadid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTIDADID() {
        return entidadid;
    }

    /**
     * Sets the value of the entidadid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTIDADID(String value) {
        this.entidadid = value;
    }

    /**
     * Gets the value of the entidadnombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTIDADNOMBRE() {
        return entidadnombre;
    }

    /**
     * Sets the value of the entidadnombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTIDADNOMBRE(String value) {
        this.entidadnombre = value;
    }

    /**
     * Gets the value of the delegadoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELEGADOID() {
        return delegadoid;
    }

    /**
     * Sets the value of the delegadoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELEGADOID(String value) {
        this.delegadoid = value;
    }

    /**
     * Gets the value of the delegadonombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELEGADONOMBRE() {
        return delegadonombre;
    }

    /**
     * Sets the value of the delegadonombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELEGADONOMBRE(String value) {
        this.delegadonombre = value;
    }

    /**
     * Gets the value of the permisos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERMISOS() {
        return permisos;
    }

    /**
     * Sets the value of the permisos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERMISOS(String value) {
        this.permisos = value;
    }

    /**
     * Gets the value of the fechainicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHAINICIO() {
        return fechainicio;
    }

    /**
     * Sets the value of the fechainicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHAINICIO(String value) {
        this.fechainicio = value;
    }

    /**
     * Gets the value of the fechafin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHAFIN() {
        return fechafin;
    }

    /**
     * Sets the value of the fechafin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHAFIN(String value) {
        this.fechafin = value;
    }

}
