//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 12:21:56 PM CET 
//


package es.caib.xml.formsconf.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}datos"/>
 *         &lt;element ref="{}propiedades"/>
 *         &lt;element ref="{}bloqueo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datos",
    "propiedades",
    "bloqueo"
})
@XmlRootElement(name = "configuracion")
public class Configuracion {

    @XmlElement(required = true)
    protected Datos datos;
    @XmlElement(required = true)
    protected Propiedades propiedades;
    @XmlElement(required = true)
    protected Bloqueo bloqueo;

    /**
     * Gets the value of the datos property.
     * 
     * @return
     *     possible object is
     *     {@link Datos }
     *     
     */
    public Datos getDatos() {
        return datos;
    }

    /**
     * Sets the value of the datos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datos }
     *     
     */
    public void setDatos(Datos value) {
        this.datos = value;
    }

    /**
     * Gets the value of the propiedades property.
     * 
     * @return
     *     possible object is
     *     {@link Propiedades }
     *     
     */
    public Propiedades getPropiedades() {
        return propiedades;
    }

    /**
     * Sets the value of the propiedades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Propiedades }
     *     
     */
    public void setPropiedades(Propiedades value) {
        this.propiedades = value;
    }

    /**
     * Gets the value of the bloqueo property.
     * 
     * @return
     *     possible object is
     *     {@link Bloqueo }
     *     
     */
    public Bloqueo getBloqueo() {
        return bloqueo;
    }

    /**
     * Sets the value of the bloqueo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bloqueo }
     *     
     */
    public void setBloqueo(Bloqueo value) {
        this.bloqueo = value;
    }

}
