ALTER TABLE ZPE_TRAPER ADD TPE_ALTGEN VARCHAR2(1) default 'N' not null;
ALTER TABLE ZPE_TRAPER ADD TPE_ALTEMA VARCHAR2(500);
ALTER TABLE ZPE_TRAPER ADD TPE_ALTSMS VARCHAR2(10);
ALTER TABLE ZPE_TRAPER ADD TPE_ALTFEC DATE;
   
comment on column ZPE_TRAPER.TPE_ALTGEN is 'INDICA SI SE GENERAN ALERTAS DE TRAMITACION (S/N)';
comment on column ZPE_TRAPER.TPE_ALTEMA is 'EMAIL PARA GENERAR ALERTAS';
comment on column ZPE_TRAPER.TPE_ALTSMS is 'SMS PARA GENERAR ALERTAS';
comment on column ZPE_TRAPER.TPE_ALTFEC is 'FECHA ULTIMA ALERTA';


ALTER table ZPE_DOCPER  ADD DPE_TIPO VARCHAR2(1);
ALTER table ZPE_DOCPER  ADD DPE_PAGTEL VARCHAR2(1) default 'N' not null;

comment on column ZPE_DOCPER.DPE_TIPO is 'TIPO DOCUMENTO: FORMULARIO (F) / PAGO (P) / ANEXO (A)';
comment on column ZPE_DOCPER.DPE_PAGTEL is 'EN CASO DE QUE SEA DE TIPO PAGO, INDICA SI ES TELEMATICO (S/N)';

ALTER table ZPE_TPEBCK ADD TPB_ALTGEN VARCHAR2(1) default 'N' not null;
ALTER TABLE ZPE_TPEBCK ADD TPB_ALTEMA VARCHAR2(500);
ALTER TABLE ZPE_TPEBCK ADD TPB_ALTSMS VARCHAR2(10);
ALTER TABLE ZPE_TPEBCK ADD TPB_ALTFEC DATE;
   
comment on column ZPE_TPEBCK.TPB_ALTGEN is 'INDICA SI SE GENERAN ALERTAS DE TRAMITACION (S/N)';
comment on column ZPE_TPEBCK.TPB_ALTEMA is 'EMAIL PARA GENERAR ALERTAS';
comment on column ZPE_TPEBCK.TPB_ALTSMS is 'SMS PARA GENERAR ALERTAS';
comment on column ZPE_TPEBCK.TPB_ALTFEC is 'FECHA ULTIMA ALERTA';


ALTER table ZPE_DPEBCK  ADD DPB_TIPO VARCHAR2(1);
ALTER table ZPE_DPEBCK  ADD DPB_PAGTEL VARCHAR2(1) default 'N' not null;

comment on column ZPE_DPEBCK.DPB_TIPO is 'TIPO DOCUMENTO: FORMULARIO (F) / PAGO (P) / ANEXO (A)';
comment on column ZPE_DPEBCK.DPB_PAGTEL is 'EN CASO DE QUE SEA DE TIPO PAGO, INDICA SI ES TELEMATICO (S/N)';
 

ALTER table ZPE_PREREG ADD PRE_ALTGEN VARCHAR2(1) default 'N' not null;
ALTER TABLE ZPE_PREREG ADD PRE_ALTEMA VARCHAR2(500);
ALTER TABLE ZPE_PREREG ADD PRE_ALTSMS VARCHAR2(10);
ALTER TABLE ZPE_PREREG ADD PRE_ALTFEC DATE;
   
comment on column ZPE_PREREG.PRE_ALTGEN is 'INDICA SI SE GENERAN ALERTAS DE TRAMITACION (S/N)';
comment on column ZPE_PREREG.PRE_ALTEMA is 'EMAIL PARA GENERAR ALERTAS';
comment on column ZPE_PREREG.PRE_ALTSMS is 'SMS PARA GENERAR ALERTAS';
comment on column ZPE_PREREG.PRE_ALTFEC is 'FECHA ULTIMA ALERTA';

ALTER table ZPE_PREBCK ADD PRB_ALTGEN VARCHAR2(1) default 'N' not null;
ALTER TABLE ZPE_PREBCK ADD PRB_ALTEMA VARCHAR2(500);
ALTER TABLE ZPE_PREBCK ADD PRB_ALTSMS VARCHAR2(10);
ALTER TABLE ZPE_PREBCK ADD PRB_ALTFEC DATE;
   
comment on column ZPE_PREBCK.PRB_ALTGEN is 'INDICA SI SE GENERAN ALERTAS DE TRAMITACION (S/N)';
comment on column ZPE_PREBCK.PRB_ALTEMA is 'EMAIL PARA GENERAR ALERTAS';
comment on column ZPE_PREBCK.PRB_ALTSMS is 'SMS PARA GENERAR ALERTAS';
comment on column ZPE_PREBCK.PRB_ALTFEC is 'FECHA ULTIMA ALERTA';
