alter table  ZPE_ENTTEL add ENT_IDEPRO  VARCHAR2(100);

comment on column ZPE_ENTTEL.ENT_IDEPRO is 'IDENTIFICADOR PROCEDIMIENTO';

alter table  ZPE_PREREG add PRE_IDEPRO  VARCHAR2(100);

comment on column ZPE_PREREG.PRE_IDEPRO is 'IDENTIFICADOR PROCEDIMIENTO';

alter table  ZPE_PREBCK add PRB_IDEPRO  VARCHAR2(100);

comment on column ZPE_PREBCK.PRB_IDEPRO is 'IDENTIFICADOR PROCEDIMIENTO';

alter table ZPE_EXPEDI  add  EXP_IDEPRO   VARCHAR2(100)  ;

UPDATE ZPE_ENTTEL SET ENT_IDEPRO = ENT_TRAMOD;
UPDATE  ZPE_PREREG SET PRE_IDEPRO = PRE_TRAMOD;
UPDATE ZPE_PREBCK SET PRB_IDEPRO = PRB_TRAMOD;

UPDATE ZPE_ENTTEL SET ENT_IDEPRO = '#DESCONOCIDO#' WHERE   ENT_IDEPRO IS NULL;
UPDATE  ZPE_PREREG SET PRE_IDEPRO = '#DESCONOCIDO#' WHERE  PRE_IDEPRO IS NULL;
UPDATE ZPE_PREBCK SET PRB_IDEPRO =  '#DESCONOCIDO#' WHERE  PRB_IDEPRO IS NULL; 

COMMIT;

CREATE VIEW TMP_TRAMITS_INI_EXPE (CODEXPE, TIPOTRAM, CODTRAM) AS
(
SELECT E1.ELE_CODEXP, E1.ELE_TIPO, E1.ELE_CODELE
FROM ZPE_ELEEX E1
WHERE E1.ELE_TIPO IN ('T', 'P') AND
 E1.ELE_FECHA = (SELECT MIN(E2.ELE_FECHA) FROM  ZPE_ELEEX E2 WHERE E2.ELE_CODEXP = E1.ELE_CODEXP) 
);

CREATE VIEW TMP_IDEPRO_EXPE (CODEXPE, IDEPRO) AS 
(
   select EXP_CODIGO, ENT_IDEPRO  FROM TMP_TRAMITS_INI_EXPE, ZPE_ENTTEL, ZPE_EXPEDI WHERE  CODEXPE =  EXP_CODIGO AND TIPOTRAM = 'T' AND ENT_CODIGO = CODTRAM
    UNION
     select EXP_CODIGO, PRE_IDEPRO  FROM TMP_TRAMITS_INI_EXPE, ZPE_PREREG, ZPE_EXPEDI WHERE  CODEXPE =  EXP_CODIGO AND TIPOTRAM = 'P'  AND PRE_CODIGO = CODTRAM  
);

update  ZPE_EXPEDI 
set EXP_IDEPRO = (SELECT IDEPRO FROM TMP_IDEPRO_EXPE WHERE CODEXPE =  EXP_CODIGO )
where EXP_NUMBTE IS NOT null;

COMMIT;

DROP VIEW TMP_IDEPRO_EXPE;
DROP VIEW TMP_TRAMITS_INI_EXPE;

update  ZPE_EXPEDI 
set EXP_IDEPRO = '#DESCONOCIDO#'
where EXP_IDEPRO IS NULL ;

COMMIT;

alter table ZPE_EXPEDI  modify  EXP_IDEPRO  not null;


UPDATE ZPE_EXPEDI  SET EXP_AVISOS = 'N' WHERE EXP_AVISOS IS NULL; 
COMMIT;

ALTER TABLE ZPE_EXPEDI MODIFY EXP_AVISOS NOT NULL;