alter table MOB_MSEMAI  add
   MSE_ACKENV           NUMBER(1)                      default 0 not null;
alter table MOB_MSEMAI  add   
   MSE_ACKEST           VARCHAR2(1);
alter table MOB_MSEMAI  add   
   MSE_ACKERR           VARCHAR2(4000);

comment on column MOB_MSEMAI.MSE_ACKENV is
'INDICA SI SE CONTROLA SI SE HA REALIZADO EL ENVIO. SOLO PERMITIDO CUANDO HAYA UN UNICO DESTINATARIO.';

comment on column MOB_MSEMAI.MSE_ACKEST is
'EN CASO DE CONTROLAR LA REALIZACION DEL ENVIO INDICA EL ESTADO';

comment on column MOB_MSEMAI.MSE_ACKERR is
'EN CASO DE CONTROLAR LA REALIZACION DEL ENVIO Y QUE EL ESTADO SEA ERRONEO INDICA EL MOTIVO DEL ERROR';


alter table MOB_MSSMS  add
   MSS_ACKENV           NUMBER(1)                      default 0 not null;
alter table MOB_MSSMS  add   
   MSS_ACKEST           VARCHAR2(1);
alter table MOB_MSSMS  add   
   MSS_ACKERR           VARCHAR2(4000);
   

comment on column MOB_MSSMS.MSS_ACKENV is
'INDICA SI SE CONTROLA SI SE HA REALIZADO EL ENVIO. SOLO PERMITIDO CUANDO HAYA UN UNICO DESTINATARIO.';

comment on column MOB_MSSMS.MSS_ACKEST is
'EN CASO DE CONTROLAR LA REALIZACION DEL ENVIO INDICA EL ESTADO';

comment on column MOB_MSSMS.MSS_ACKERR is
'EN CASO DE CONTROLAR LA REALIZACION DEL ENVIO Y QUE EL ESTADO SEA ERRONEO INDICA EL MOTIVO DEL ERROR';   
