//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.23 at 09:16:32 AM CEST 
//


package es.caib.xml.oficioremision.modelo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caib.xml.oficioremision.modelo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TEXTO_QNAME = new QName("", "TEXTO");
    private final static QName _TITULO_QNAME = new QName("", "TITULO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.xml.oficioremision.modelo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OFICIOREMISION }
     * 
     */
    public OFICIOREMISION createOFICIOREMISION() {
        return new OFICIOREMISION();
    }

    /**
     * Create an instance of {@link PARAMETROTRAMITE }
     * 
     */
    public PARAMETROTRAMITE createPARAMETROTRAMITE() {
        return new PARAMETROTRAMITE();
    }

    /**
     * Create an instance of {@link PARAMETROSTRAMITE }
     * 
     */
    public PARAMETROSTRAMITE createPARAMETROSTRAMITE() {
        return new PARAMETROSTRAMITE();
    }

    /**
     * Create an instance of {@link TRAMITESUBSANACION }
     * 
     */
    public TRAMITESUBSANACION createTRAMITESUBSANACION() {
        return new TRAMITESUBSANACION();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXTO")
    public JAXBElement<String> createTEXTO(String value) {
        return new JAXBElement<String>(_TEXTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TITULO")
    public JAXBElement<String> createTITULO(String value) {
        return new JAXBElement<String>(_TITULO_QNAME, String.class, null, value);
    }

}
