package es.caib.zonaper.ws.v2.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Mon Feb 03 22:12:00 CET 2014
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:zonaper:ws:v2:services", name = "BackofficeFacade")
@XmlSeeAlso({es.caib.zonaper.ws.v2.model.ObjectFactory.class})
public interface BackofficeFacade {

    @ResponseWrapper(localName = "obtenerEstadoPagosTramiteResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.ObtenerEstadoPagosTramiteResponse")
    @RequestWrapper(localName = "obtenerEstadoPagosTramite", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.ObtenerEstadoPagosTramite")
    @WebResult(name = "obtenerEstadoPagosTramiteReturn", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
    @WebMethod
    public es.caib.zonaper.ws.v2.model.EstadoPagos obtenerEstadoPagosTramite(
        @WebParam(name = "identificadorPersistenciaTramite", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        java.lang.String identificadorPersistenciaTramite
    ) throws BackofficeFacadeException;

    @ResponseWrapper(localName = "altaEventoExpedienteResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.AltaEventoExpedienteResponse")
    @RequestWrapper(localName = "altaEventoExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.AltaEventoExpediente")
    @WebMethod
    public void altaEventoExpediente(
        @WebParam(name = "unidadAdministrativa", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        long unidadAdministrativa,
        @WebParam(name = "identificadorExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        java.lang.String identificadorExpediente,
        @WebParam(name = "claveExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        java.lang.String claveExpediente,
        @WebParam(name = "evento", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        es.caib.zonaper.ws.v2.model.EventoExpediente evento
    ) throws BackofficeFacadeException;

    @ResponseWrapper(localName = "altaZonaPersonalUsuarioResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.AltaZonaPersonalUsuarioResponse")
    @RequestWrapper(localName = "altaZonaPersonalUsuario", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.AltaZonaPersonalUsuario")
    @WebResult(name = "altaZonaPersonalUsuarioReturn", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
    @WebMethod
    public java.lang.String altaZonaPersonalUsuario(
        @WebParam(name = "nif", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        java.lang.String nif,
        @WebParam(name = "nombre", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        java.lang.String nombre,
        @WebParam(name = "apellido1", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        java.lang.String apellido1,
        @WebParam(name = "apellido2", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        java.lang.String apellido2
    ) throws BackofficeFacadeException;

    @ResponseWrapper(localName = "existeZonaPersonalUsuarioResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.ExisteZonaPersonalUsuarioResponse")
    @RequestWrapper(localName = "existeZonaPersonalUsuario", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.ExisteZonaPersonalUsuario")
    @WebResult(name = "existeZonaPersonalUsuarioReturn", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
    @WebMethod
    public boolean existeZonaPersonalUsuario(
        @WebParam(name = "nifUsuario", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        java.lang.String nifUsuario
    ) throws BackofficeFacadeException;

    @ResponseWrapper(localName = "altaExpedienteResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.AltaExpedienteResponse")
    @RequestWrapper(localName = "altaExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.zonaper.ws.v2.model.AltaExpediente")
    @WebResult(name = "altaExpedienteReturn", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
    @WebMethod
    public java.lang.String altaExpediente(
        @WebParam(name = "expediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        es.caib.zonaper.ws.v2.model.Expediente expediente
    ) throws BackofficeFacadeException;
}
