package es.caib.sistra.model;
// Generated 21-mar-2006 11:41:40 by Hibernate Tools 3.1.0 beta3



/**
 * StrTradjs generated by hbm2java
 */

public class TraDatoJustificante  implements Traduccion {


    // Fields         
     private String descripcion;

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

     
     
}
