//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 05:57:23 PM CEST 
//


package es.caib.xml.avisonotificacion.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TITULO"/>
 *         &lt;element ref="{}TEXTO"/>
 *         &lt;element ref="{}TEXTO_SMS" minOccurs="0"/>
 *         &lt;element ref="{}ACUSE_RECIBO"/>
 *         &lt;element ref="{}PLAZO" minOccurs="0"/>
 *         &lt;element ref="{}ACCESIBLE_POR_CLAVE" minOccurs="0"/>
 *         &lt;element ref="{}EXPEDIENTE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titulo",
    "texto",
    "textosms",
    "acuserecibo",
    "plazo",
    "accesibleporclave",
    "expediente"
})
@XmlRootElement(name = "AVISO_NOTIFICACION")
public class AVISONOTIFICACION {

    @XmlElement(name = "TITULO", required = true)
    protected String titulo;
    @XmlElement(name = "TEXTO", required = true)
    protected String texto;
    @XmlElement(name = "TEXTO_SMS")
    protected String textosms;
    @XmlElement(name = "ACUSE_RECIBO", required = true)
    protected String acuserecibo;
    @XmlElement(name = "PLAZO")
    protected String plazo;
    @XmlElement(name = "ACCESIBLE_POR_CLAVE")
    protected String accesibleporclave;
    @XmlElement(name = "EXPEDIENTE", required = true)
    protected EXPEDIENTE expediente;

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITULO() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITULO(String value) {
        this.titulo = value;
    }

    /**
     * Gets the value of the texto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTO() {
        return texto;
    }

    /**
     * Sets the value of the texto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTO(String value) {
        this.texto = value;
    }

    /**
     * Gets the value of the textosms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTOSMS() {
        return textosms;
    }

    /**
     * Sets the value of the textosms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTOSMS(String value) {
        this.textosms = value;
    }

    /**
     * Gets the value of the acuserecibo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACUSERECIBO() {
        return acuserecibo;
    }

    /**
     * Sets the value of the acuserecibo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACUSERECIBO(String value) {
        this.acuserecibo = value;
    }

    /**
     * Gets the value of the plazo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLAZO() {
        return plazo;
    }

    /**
     * Sets the value of the plazo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLAZO(String value) {
        this.plazo = value;
    }

    /**
     * Gets the value of the accesibleporclave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCESIBLEPORCLAVE() {
        return accesibleporclave;
    }

    /**
     * Sets the value of the accesibleporclave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCESIBLEPORCLAVE(String value) {
        this.accesibleporclave = value;
    }

    /**
     * Gets the value of the expediente property.
     * 
     * @return
     *     possible object is
     *     {@link EXPEDIENTE }
     *     
     */
    public EXPEDIENTE getEXPEDIENTE() {
        return expediente;
    }

    /**
     * Sets the value of the expediente property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXPEDIENTE }
     *     
     */
    public void setEXPEDIENTE(EXPEDIENTE value) {
        this.expediente = value;
    }

}
