alter table ZPE_DOCHIE  add DHE_ORDEN            NUMBER(2);
comment on column ZPE_DOCHIE.DHE_ORDEN is 'Orden';

alter table ZPE_DOCNOT  add  DNO_ORDEN            NUMBER(2);
comment on column ZPE_DOCNOT.DNO_ORDEN is 'Orden';

-- Modificar tabla de pagos
ALTER TABLE ZONAPER.ZPE_RPAGOS
MODIFY(PAG_NOMTRA VARCHAR2(200 BYTE));

ALTER TABLE ZONAPER.ZPE_RPAGOS
MODIFY(PAG_CONCEP VARCHAR2(200 BYTE));

ALTER TABLE ZONAPER.ZPE_RPAGOS
MODIFY(PAG_IDENTP VARCHAR2(200 BYTE));

ALTER TABLE ZONAPER.ZPE_RPAGOS
MODIFY(PAG_URLSTR VARCHAR2(400 BYTE));

ALTER TABLE ZONAPER.ZPE_RPAGOS
MODIFY(PAG_URLMNT VARCHAR2(400 BYTE));

