//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.07 at 08:58:59 AM CEST 
//


package es.caib.xml.taxa.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NIF"/>
 *         &lt;element ref="{}NOM"/>
 *         &lt;element ref="{}DOMICILI" minOccurs="0"/>
 *         &lt;element ref="{}TELEFON" minOccurs="0"/>
 *         &lt;element ref="{}FAX" minOccurs="0"/>
 *         &lt;element ref="{}LOCALITAT" minOccurs="0"/>
 *         &lt;element ref="{}PROVINCIA" minOccurs="0"/>
 *         &lt;element ref="{}CODI_POSTAL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nif",
    "nom",
    "domicili",
    "telefon",
    "fax",
    "localitat",
    "provincia",
    "codipostal"
})
@XmlRootElement(name = "DECLARANT")
public class DECLARANT {

    @XmlElement(name = "NIF", required = true)
    protected NIF nif;
    @XmlElement(name = "NOM", required = true)
    protected NOM nom;
    @XmlElement(name = "DOMICILI")
    protected DOMICILI domicili;
    @XmlElement(name = "TELEFON")
    protected TELEFON telefon;
    @XmlElement(name = "FAX")
    protected FAX fax;
    @XmlElement(name = "LOCALITAT")
    protected LOCALITAT localitat;
    @XmlElement(name = "PROVINCIA")
    protected PROVINCIA provincia;
    @XmlElement(name = "CODI_POSTAL")
    protected CODIPOSTAL codipostal;

    /**
     * Gets the value of the nif property.
     * 
     * @return
     *     possible object is
     *     {@link NIF }
     *     
     */
    public NIF getNIF() {
        return nif;
    }

    /**
     * Sets the value of the nif property.
     * 
     * @param value
     *     allowed object is
     *     {@link NIF }
     *     
     */
    public void setNIF(NIF value) {
        this.nif = value;
    }

    /**
     * Gets the value of the nom property.
     * 
     * @return
     *     possible object is
     *     {@link NOM }
     *     
     */
    public NOM getNOM() {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     * 
     * @param value
     *     allowed object is
     *     {@link NOM }
     *     
     */
    public void setNOM(NOM value) {
        this.nom = value;
    }

    /**
     * Gets the value of the domicili property.
     * 
     * @return
     *     possible object is
     *     {@link DOMICILI }
     *     
     */
    public DOMICILI getDOMICILI() {
        return domicili;
    }

    /**
     * Sets the value of the domicili property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOMICILI }
     *     
     */
    public void setDOMICILI(DOMICILI value) {
        this.domicili = value;
    }

    /**
     * Gets the value of the telefon property.
     * 
     * @return
     *     possible object is
     *     {@link TELEFON }
     *     
     */
    public TELEFON getTELEFON() {
        return telefon;
    }

    /**
     * Sets the value of the telefon property.
     * 
     * @param value
     *     allowed object is
     *     {@link TELEFON }
     *     
     */
    public void setTELEFON(TELEFON value) {
        this.telefon = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link FAX }
     *     
     */
    public FAX getFAX() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link FAX }
     *     
     */
    public void setFAX(FAX value) {
        this.fax = value;
    }

    /**
     * Gets the value of the localitat property.
     * 
     * @return
     *     possible object is
     *     {@link LOCALITAT }
     *     
     */
    public LOCALITAT getLOCALITAT() {
        return localitat;
    }

    /**
     * Sets the value of the localitat property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOCALITAT }
     *     
     */
    public void setLOCALITAT(LOCALITAT value) {
        this.localitat = value;
    }

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link PROVINCIA }
     *     
     */
    public PROVINCIA getPROVINCIA() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROVINCIA }
     *     
     */
    public void setPROVINCIA(PROVINCIA value) {
        this.provincia = value;
    }

    /**
     * Gets the value of the codipostal property.
     * 
     * @return
     *     possible object is
     *     {@link CODIPOSTAL }
     *     
     */
    public CODIPOSTAL getCODIPOSTAL() {
        return codipostal;
    }

    /**
     * Sets the value of the codipostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODIPOSTAL }
     *     
     */
    public void setCODIPOSTAL(CODIPOSTAL value) {
        this.codipostal = value;
    }

}
