INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, EXP_NIFRTE, 'E', EXP_CODIGO, 'Número expediente', EXP_IDEXP FROM ZPE_EXPEDI
                    WHERE EXP_SEYCIU IS NOT NULL AND EXP_NIFRTE IS NOT NULL;

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, EXP_NIFRTE, 'E', EXP_CODIGO, 'Título', EXP_DESC FROM ZPE_EXPEDI
                    WHERE EXP_SEYCIU IS NOT NULL  AND EXP_NIFRTE IS NOT NULL;

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, EXP_NIFRTE, 'E', EXP_CODIGO, 'Nif representado', EXP_NIFRDO FROM ZPE_EXPEDI
                    WHERE EXP_SEYCIU IS NOT NULL  AND EXP_NIFRTE IS NOT NULL AND EXP_NIFRDO IS NOT NULL;

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, EXP_NIFRTE, 'E', EXP_CODIGO, 'Nombre representado', EXP_NOMRDO FROM ZPE_EXPEDI
                    WHERE EXP_SEYCIU IS NOT NULL  AND EXP_NIFRTE IS NOT NULL AND EXP_NOMRDO IS NOT NULL;        