/* ENTRADAS TELEMATICAS */
INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, ENT_NIFRTE, 'T', ENT_CODIGO, 'Número registro', ENT_NUMREG
    FROM ZPE_ENTTEL 
				WHERE ENT_NIVAUT <> 'A' AND ENT_NIFRTE IS NOT NULL;
				
INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, ENT_NIFRTE, 'T', ENT_CODIGO, 'Título trámite', ENT_DESC
    FROM ZPE_ENTTEL 
				WHERE ENT_NIVAUT <> 'A'  AND ENT_NIFRTE IS NOT NULL;

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, ENT_NIFRTE, 'T', ENT_CODIGO, 'Nif representado', ENT_NIFRDO
    FROM ZPE_ENTTEL 
				WHERE ENT_NIVAUT <> 'A' AND ENT_NIFRTE IS NOT NULL AND ENT_NIFRDO IS NOT NULL;

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, ENT_NIFRTE, 'T', ENT_CODIGO, 'Nombre representado', ENT_NOMRDO
    FROM ZPE_ENTTEL 
				WHERE ENT_NIVAUT <> 'A' AND ENT_NIFRTE IS NOT NULL AND ENT_NOMRDO IS NOT NULL;
				
/* DOCS ENTRADAS TELEMATICAS */
INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
  SELECT ZPE_SEQIND.NEXTVAL, ENT_NIFRTE, 'T', ENT_CODIGO, DEN_DOCIDE || '(' || TO_CHAR(DEN_DOCNUM) || ')', DEN_DESC
    FROM ZPE_ENTTEL, ZPE_DOCENT
      WHERE 
        ENT_NIVAUT <> 'A'  AND ENT_NIFRTE IS NOT NULL  AND ENT_CODIGO =  DEN_CODENT AND DEN_DOCIDE <> 'DTP';
        


			
				
				