//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 12:21:56 PM CET 
//


package es.caib.xml.formsconf.modelo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caib.xml.formsconf.modelo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Idioma_QNAME = new QName("", "idioma");
    private final static QName _NomParamXMLDatosIni_QNAME = new QName("", "nomParamXMLDatosIni");
    private final static QName _NomParamXMLDatosFin_QNAME = new QName("", "nomParamXMLDatosFin");
    private final static QName _UrlRedireccionCancel_QNAME = new QName("", "urlRedireccionCancel");
    private final static QName _Layout_QNAME = new QName("", "layout");
    private final static QName _UrlSisTraMantenimientoSesion_QNAME = new QName("", "urlSisTraMantenimientoSesion");
    private final static QName _Xpath_QNAME = new QName("", "xpath");
    private final static QName _Valor_QNAME = new QName("", "valor");
    private final static QName _Modelo_QNAME = new QName("", "modelo");
    private final static QName _Version_QNAME = new QName("", "version");
    private final static QName _GuardarSinTerminar_QNAME = new QName("", "guardarSinTerminar");
    private final static QName _Nombre_QNAME = new QName("", "nombre");
    private final static QName _UrlRedireccionOK_QNAME = new QName("", "urlRedireccionOK");
    private final static QName _UrlSisTraOK_QNAME = new QName("", "urlSisTraOK");
    private final static QName _NomParamXMLSinTerminar_QNAME = new QName("", "nomParamXMLSinTerminar");
    private final static QName _UrlSisTraCancel_QNAME = new QName("", "urlSisTraCancel");
    private final static QName _CodigoPerfil_QNAME = new QName("", "codigoPerfil");
    private final static QName _NomParamTokenRetorno_QNAME = new QName("", "nomParamTokenRetorno");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.xml.formsconf.modelo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Propiedades }
     * 
     */
    public Propiedades createPropiedades() {
        return new Propiedades();
    }

    /**
     * Create an instance of {@link Bloqueo }
     * 
     */
    public Bloqueo createBloqueo() {
        return new Bloqueo();
    }

    /**
     * Create an instance of {@link Datos }
     * 
     */
    public Datos createDatos() {
        return new Datos();
    }

    /**
     * Create an instance of {@link Configuracion }
     * 
     */
    public Configuracion createConfiguracion() {
        return new Configuracion();
    }

    /**
     * Create an instance of {@link Propiedad }
     * 
     */
    public Propiedad createPropiedad() {
        return new Propiedad();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "idioma")
    public JAXBElement<String> createIdioma(String value) {
        return new JAXBElement<String>(_Idioma_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nomParamXMLDatosIni")
    public JAXBElement<String> createNomParamXMLDatosIni(String value) {
        return new JAXBElement<String>(_NomParamXMLDatosIni_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nomParamXMLDatosFin")
    public JAXBElement<String> createNomParamXMLDatosFin(String value) {
        return new JAXBElement<String>(_NomParamXMLDatosFin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlRedireccionCancel")
    public JAXBElement<String> createUrlRedireccionCancel(String value) {
        return new JAXBElement<String>(_UrlRedireccionCancel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "layout")
    public JAXBElement<String> createLayout(String value) {
        return new JAXBElement<String>(_Layout_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlSisTraMantenimientoSesion")
    public JAXBElement<String> createUrlSisTraMantenimientoSesion(String value) {
        return new JAXBElement<String>(_UrlSisTraMantenimientoSesion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xpath")
    public JAXBElement<String> createXpath(String value) {
        return new JAXBElement<String>(_Xpath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valor")
    public JAXBElement<String> createValor(String value) {
        return new JAXBElement<String>(_Valor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modelo")
    public JAXBElement<String> createModelo(String value) {
        return new JAXBElement<String>(_Modelo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<Integer> createVersion(Integer value) {
        return new JAXBElement<Integer>(_Version_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "guardarSinTerminar")
    public JAXBElement<String> createGuardarSinTerminar(String value) {
        return new JAXBElement<String>(_GuardarSinTerminar_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nombre")
    public JAXBElement<String> createNombre(String value) {
        return new JAXBElement<String>(_Nombre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlRedireccionOK")
    public JAXBElement<String> createUrlRedireccionOK(String value) {
        return new JAXBElement<String>(_UrlRedireccionOK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlSisTraOK")
    public JAXBElement<String> createUrlSisTraOK(String value) {
        return new JAXBElement<String>(_UrlSisTraOK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nomParamXMLSinTerminar")
    public JAXBElement<String> createNomParamXMLSinTerminar(String value) {
        return new JAXBElement<String>(_NomParamXMLSinTerminar_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlSisTraCancel")
    public JAXBElement<String> createUrlSisTraCancel(String value) {
        return new JAXBElement<String>(_UrlSisTraCancel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codigoPerfil")
    public JAXBElement<String> createCodigoPerfil(String value) {
        return new JAXBElement<String>(_CodigoPerfil_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nomParamTokenRetorno")
    public JAXBElement<String> createNomParamTokenRetorno(String value) {
        return new JAXBElement<String>(_NomParamTokenRetorno_QNAME, String.class, null, value);
    }

}
