//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.07 at 08:58:49 AM CEST 
//


package es.caib.xml.registro.modelo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caib.xml.registro.modelo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EXTRACTODOCUMENTO_QNAME = new QName("", "EXTRACTO_DOCUMENTO");
    private final static QName _IDENTIFICACIONINTERESADO_QNAME = new QName("", "IDENTIFICACION_INTERESADO");
    private final static QName _TIPOREGISTRO_QNAME = new QName("", "TIPO_REGISTRO");
    private final static QName _USUARIOSEYCON_QNAME = new QName("", "USUARIO_SEYCON");
    private final static QName _DECODIFICACIONENTIDADREGISTRALDESTINO_QNAME = new QName("", "DECODIFICACION_ENTIDAD_REGISTRAL_DESTINO");
    private final static QName _FAX_QNAME = new QName("", "FAX");
    private final static QName _TIPODEDOCUMENTO_QNAME = new QName("", "TIPO_DE_DOCUMENTO");
    private final static QName _ESTRUCTURADO_QNAME = new QName("", "ESTRUCTURADO");
    private final static QName _CODIGOPROVINCIA_QNAME = new QName("", "CODIGO_PROVINCIA");
    private final static QName _EXTRACTOASUNTO_QNAME = new QName("", "EXTRACTO_ASUNTO");
    private final static QName _CODIGOORGANODESTINO_QNAME = new QName("", "CODIGO_ORGANO_DESTINO");
    private final static QName _CODIGONORMALIZADO_QNAME = new QName("", "CODIGO_NORMALIZADO");
    private final static QName _DOMICILIO_QNAME = new QName("", "DOMICILIO");
    private final static QName _NUMEROIDENTIFICACION_QNAME = new QName("", "NUMERO_IDENTIFICACION");
    private final static QName _FECHAASUNTO_QNAME = new QName("", "FECHA_ASUNTO");
    private final static QName _FIRMATERCEROS_QNAME = new QName("", "FIRMA_TERCEROS");
    private final static QName _CODIGORDS_QNAME = new QName("", "CODIGO_RDS");
    private final static QName _CODIGOPOSTAL_QNAME = new QName("", "CODIGO_POSTAL");
    private final static QName _TIPOASUNTO_QNAME = new QName("", "TIPO_ASUNTO");
    private final static QName _IDIOMAASUNTO_QNAME = new QName("", "IDIOMA_ASUNTO");
    private final static QName _FORMATODATOSINTERESADO_QNAME = new QName("", "FORMATO_DATOS_INTERESADO");
    private final static QName _NIVELAUTENTICACION_QNAME = new QName("", "NIVEL_AUTENTICACION");
    private final static QName _IDENTIFICADORDOCUMENTO_QNAME = new QName("", "IDENTIFICADOR_DOCUMENTO");
    private final static QName _DESCRIPCIONORGANODESTINO_QNAME = new QName("", "DESCRIPCION_ORGANO_DESTINO");
    private final static QName _NOMBREMUNICIPIO_QNAME = new QName("", "NOMBRE_MUNICIPIO");
    private final static QName _DESCRIPCIONDOCUMENTO_QNAME = new QName("", "DESCRIPCION_DOCUMENTO");
    private final static QName _NUMEROREGISTRO_QNAME = new QName("", "NUMERO_REGISTRO");
    private final static QName _CODIGOMUNICIPIO_QNAME = new QName("", "CODIGO_MUNICIPIO");
    private final static QName _TIPOINTERESADO_QNAME = new QName("", "TIPO_INTERESADO");
    private final static QName _TIPOIDENTIFICACION_QNAME = new QName("", "TIPO_IDENTIFICACION");
    private final static QName _IDENTIFICADORTRAMITE_QNAME = new QName("", "IDENTIFICADOR_TRAMITE");
    private final static QName _CODIGOENTIDADREGISTRALORIGEN_QNAME = new QName("", "CODIGO_ENTIDAD_REGISTRAL_ORIGEN");
    private final static QName _CODIGOPOBLACION_QNAME = new QName("", "CODIGO_POBLACION");
    private final static QName _NOMBREPOBLACION_QNAME = new QName("", "NOMBRE_POBLACION");
    private final static QName _CODIGOENTIDADREGISTRALDESTINO_QNAME = new QName("", "CODIGO_ENTIDAD_REGISTRAL_DESTINO");
    private final static QName _TELEFONO_QNAME = new QName("", "TELEFONO");
    private final static QName _PAISORIGEN_QNAME = new QName("", "PAIS_ORIGEN");
    private final static QName _FECHAENTRADAREGISTRO_QNAME = new QName("", "FECHA_ENTRADA_REGISTRO");
    private final static QName _HASHDOCUMENTO_QNAME = new QName("", "HASH_DOCUMENTO");
    private final static QName _NOMBREDOCUMENTO_QNAME = new QName("", "NOMBRE_DOCUMENTO");
    private final static QName _CODIGOUNIDADADMINISTRATIVA_QNAME = new QName("", "CODIGO_UNIDAD_ADMINISTRATIVA");
    private final static QName _FECHAREGISTRO_QNAME = new QName("", "FECHA_REGISTRO");
    private final static QName _NOMBREPROVINCIA_QNAME = new QName("", "NOMBRE_PROVINCIA");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.xml.registro.modelo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DATOSANEXODOCUMENTACION }
     * 
     */
    public DATOSANEXODOCUMENTACION createDATOSANEXODOCUMENTACION() {
        return new DATOSANEXODOCUMENTACION();
    }

    /**
     * Create an instance of {@link DATOSDESTINO }
     * 
     */
    public DATOSDESTINO createDATOSDESTINO() {
        return new DATOSDESTINO();
    }

    /**
     * Create an instance of {@link DATOSINTERESADO }
     * 
     */
    public DATOSINTERESADO createDATOSINTERESADO() {
        return new DATOSINTERESADO();
    }

    /**
     * Create an instance of {@link ASIENTOREGISTRAL }
     * 
     */
    public ASIENTOREGISTRAL createASIENTOREGISTRAL() {
        return new ASIENTOREGISTRAL();
    }

    /**
     * Create an instance of {@link DATOSASUNTO }
     * 
     */
    public DATOSASUNTO createDATOSASUNTO() {
        return new DATOSASUNTO();
    }

    /**
     * Create an instance of {@link DIRECCIONCODIFICADA }
     * 
     */
    public DIRECCIONCODIFICADA createDIRECCIONCODIFICADA() {
        return new DIRECCIONCODIFICADA();
    }

    /**
     * Create an instance of {@link DATOSORIGEN }
     * 
     */
    public DATOSORIGEN createDATOSORIGEN() {
        return new DATOSORIGEN();
    }

    /**
     * Create an instance of {@link JUSTIFICANTE }
     * 
     */
    public JUSTIFICANTE createJUSTIFICANTE() {
        return new JUSTIFICANTE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXTRACTO_DOCUMENTO")
    public JAXBElement<String> createEXTRACTODOCUMENTO(String value) {
        return new JAXBElement<String>(_EXTRACTODOCUMENTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IDENTIFICACION_INTERESADO")
    public JAXBElement<String> createIDENTIFICACIONINTERESADO(String value) {
        return new JAXBElement<String>(_IDENTIFICACIONINTERESADO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIPO_REGISTRO")
    public JAXBElement<String> createTIPOREGISTRO(String value) {
        return new JAXBElement<String>(_TIPOREGISTRO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "USUARIO_SEYCON")
    public JAXBElement<String> createUSUARIOSEYCON(String value) {
        return new JAXBElement<String>(_USUARIOSEYCON_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DECODIFICACION_ENTIDAD_REGISTRAL_DESTINO")
    public JAXBElement<String> createDECODIFICACIONENTIDADREGISTRALDESTINO(String value) {
        return new JAXBElement<String>(_DECODIFICACIONENTIDADREGISTRALDESTINO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FAX")
    public JAXBElement<String> createFAX(String value) {
        return new JAXBElement<String>(_FAX_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIPO_DE_DOCUMENTO")
    public JAXBElement<String> createTIPODEDOCUMENTO(String value) {
        return new JAXBElement<String>(_TIPODEDOCUMENTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ESTRUCTURADO")
    public JAXBElement<String> createESTRUCTURADO(String value) {
        return new JAXBElement<String>(_ESTRUCTURADO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_PROVINCIA")
    public JAXBElement<String> createCODIGOPROVINCIA(String value) {
        return new JAXBElement<String>(_CODIGOPROVINCIA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXTRACTO_ASUNTO")
    public JAXBElement<String> createEXTRACTOASUNTO(String value) {
        return new JAXBElement<String>(_EXTRACTOASUNTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_ORGANO_DESTINO")
    public JAXBElement<String> createCODIGOORGANODESTINO(String value) {
        return new JAXBElement<String>(_CODIGOORGANODESTINO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_NORMALIZADO")
    public JAXBElement<String> createCODIGONORMALIZADO(String value) {
        return new JAXBElement<String>(_CODIGONORMALIZADO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOMICILIO")
    public JAXBElement<String> createDOMICILIO(String value) {
        return new JAXBElement<String>(_DOMICILIO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NUMERO_IDENTIFICACION")
    public JAXBElement<String> createNUMEROIDENTIFICACION(String value) {
        return new JAXBElement<String>(_NUMEROIDENTIFICACION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FECHA_ASUNTO")
    public JAXBElement<String> createFECHAASUNTO(String value) {
        return new JAXBElement<String>(_FECHAASUNTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIRMA_TERCEROS")
    public JAXBElement<String> createFIRMATERCEROS(String value) {
        return new JAXBElement<String>(_FIRMATERCEROS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_RDS")
    public JAXBElement<String> createCODIGORDS(String value) {
        return new JAXBElement<String>(_CODIGORDS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_POSTAL")
    public JAXBElement<String> createCODIGOPOSTAL(String value) {
        return new JAXBElement<String>(_CODIGOPOSTAL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIPO_ASUNTO")
    public JAXBElement<String> createTIPOASUNTO(String value) {
        return new JAXBElement<String>(_TIPOASUNTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IDIOMA_ASUNTO")
    public JAXBElement<String> createIDIOMAASUNTO(String value) {
        return new JAXBElement<String>(_IDIOMAASUNTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FORMATO_DATOS_INTERESADO")
    public JAXBElement<String> createFORMATODATOSINTERESADO(String value) {
        return new JAXBElement<String>(_FORMATODATOSINTERESADO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NIVEL_AUTENTICACION")
    public JAXBElement<String> createNIVELAUTENTICACION(String value) {
        return new JAXBElement<String>(_NIVELAUTENTICACION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IDENTIFICADOR_DOCUMENTO")
    public JAXBElement<String> createIDENTIFICADORDOCUMENTO(String value) {
        return new JAXBElement<String>(_IDENTIFICADORDOCUMENTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DESCRIPCION_ORGANO_DESTINO")
    public JAXBElement<String> createDESCRIPCIONORGANODESTINO(String value) {
        return new JAXBElement<String>(_DESCRIPCIONORGANODESTINO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NOMBRE_MUNICIPIO")
    public JAXBElement<String> createNOMBREMUNICIPIO(String value) {
        return new JAXBElement<String>(_NOMBREMUNICIPIO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DESCRIPCION_DOCUMENTO")
    public JAXBElement<String> createDESCRIPCIONDOCUMENTO(String value) {
        return new JAXBElement<String>(_DESCRIPCIONDOCUMENTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NUMERO_REGISTRO")
    public JAXBElement<String> createNUMEROREGISTRO(String value) {
        return new JAXBElement<String>(_NUMEROREGISTRO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_MUNICIPIO")
    public JAXBElement<String> createCODIGOMUNICIPIO(String value) {
        return new JAXBElement<String>(_CODIGOMUNICIPIO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIPO_INTERESADO")
    public JAXBElement<String> createTIPOINTERESADO(String value) {
        return new JAXBElement<String>(_TIPOINTERESADO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIPO_IDENTIFICACION")
    public JAXBElement<String> createTIPOIDENTIFICACION(String value) {
        return new JAXBElement<String>(_TIPOIDENTIFICACION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IDENTIFICADOR_TRAMITE")
    public JAXBElement<String> createIDENTIFICADORTRAMITE(String value) {
        return new JAXBElement<String>(_IDENTIFICADORTRAMITE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_ENTIDAD_REGISTRAL_ORIGEN")
    public JAXBElement<String> createCODIGOENTIDADREGISTRALORIGEN(String value) {
        return new JAXBElement<String>(_CODIGOENTIDADREGISTRALORIGEN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_POBLACION")
    public JAXBElement<String> createCODIGOPOBLACION(String value) {
        return new JAXBElement<String>(_CODIGOPOBLACION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NOMBRE_POBLACION")
    public JAXBElement<String> createNOMBREPOBLACION(String value) {
        return new JAXBElement<String>(_NOMBREPOBLACION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_ENTIDAD_REGISTRAL_DESTINO")
    public JAXBElement<String> createCODIGOENTIDADREGISTRALDESTINO(String value) {
        return new JAXBElement<String>(_CODIGOENTIDADREGISTRALDESTINO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TELEFONO")
    public JAXBElement<String> createTELEFONO(String value) {
        return new JAXBElement<String>(_TELEFONO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PAIS_ORIGEN")
    public JAXBElement<String> createPAISORIGEN(String value) {
        return new JAXBElement<String>(_PAISORIGEN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FECHA_ENTRADA_REGISTRO")
    public JAXBElement<String> createFECHAENTRADAREGISTRO(String value) {
        return new JAXBElement<String>(_FECHAENTRADAREGISTRO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HASH_DOCUMENTO")
    public JAXBElement<String> createHASHDOCUMENTO(String value) {
        return new JAXBElement<String>(_HASHDOCUMENTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NOMBRE_DOCUMENTO")
    public JAXBElement<String> createNOMBREDOCUMENTO(String value) {
        return new JAXBElement<String>(_NOMBREDOCUMENTO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODIGO_UNIDAD_ADMINISTRATIVA")
    public JAXBElement<String> createCODIGOUNIDADADMINISTRATIVA(String value) {
        return new JAXBElement<String>(_CODIGOUNIDADADMINISTRATIVA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FECHA_REGISTRO")
    public JAXBElement<String> createFECHAREGISTRO(String value) {
        return new JAXBElement<String>(_FECHAREGISTRO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NOMBRE_PROVINCIA")
    public JAXBElement<String> createNOMBREPROVINCIA(String value) {
        return new JAXBElement<String>(_NOMBREPROVINCIA_QNAME, String.class, null, value);
    }

}
