ALTER TABLE BTE_TRAAPL ADD TAP_WSVER  VARCHAR(10);
update BTE_TRAAPL set TAP_WSVER = 'v1' where TAP_TIPACC = 'W';

ALTER TABLE BTE_TRAAPL ADD TAP_ERRORS bytea;

ALTER table BTE_TRAMIT ADD TRA_NIFDLG VARCHAR(12);
ALTER table BTE_TRAMIT ADD TRA_NOMDLG VARCHAR(500);

ALTER TABLE BTE_TRAMIT ADD TRA_SBEXID VARCHAR(50);
ALTER TABLE BTE_TRAMIT ADD TRA_SBEXUA INT8;

ALTER TABLE BTE_TRAAPL ALTER COLUMN TAP_IDETRA TYPE VARCHAR(20);
ALTER TABLE BTE_TRAMIT ALTER COLUMN TRA_IDETRA TYPE VARCHAR(20);

ALTER TABLE BTE_FICEXP  ALTER COLUMN FIC_IDETRA VARCHAR2(20); 
ALTER TABLE BTE_GESTRA  ALTER COLUMN GAP_IDETRA VARCHAR2(20); 

