package es.caib.redose.model;
// Generated 07-mar-2006 18:19:34 by Hibernate Tools 3.1.0 beta3



/**
 * Fichero generated by hbm2java
 */

public class Fichero  implements java.io.Serializable {


    // Fields    

     private Long codigo;
     private byte[] datos;


    // Constructors

    /** default constructor */
    public Fichero() {
    }

    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long ficCodigo) {
        this.codigo = ficCodigo;
    }

    public byte[] getDatos() {
        return this.datos;
    }
    
    public void setDatos(byte[] ficDatos) {
        this.datos = ficDatos;
    }
   








}
