INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_NOM, USU_NIF) 
VALUES ( 'admin', 'admin' , 'Usuario administrador' ,null );

INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_NOM, USU_NIF) 
VALUES ( 'gestor', 'gestor' , 'Usuario gestor' ,null );

INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_NOM, USU_NIF) 
VALUES ( 'registro', 'registro' , 'Usuario punto registro' ,null );

INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_NOM, USU_NIF) 
VALUES ( 'helpdesk', 'helpdesk' , 'Usuario HelpDesk' ,null );

INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_NOM, USU_NIF) 
VALUES ( 'auto', 'auto' , 'Usuario procesos automaticos' ,null );

INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_NOM, USU_NIF) 
VALUES ( 'demo', 'demo' , 'Jose García García' ,'00000000T' );

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'tothom'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'STR_ADMIN'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'ZPE_ADMIN'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'BTE_ADMIN'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'RDS_ADMIN'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'RFR_OPERADOR'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'RFR_ADMIN'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'admin', 'MOB_ADMIN'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'gestor', 'tothom'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'gestor', 'BTE_GESTOR'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'gestor', 'MOB_GESTOR');
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'gestor', 'RTE_GESTOR');
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'gestor', 'AUD_GESTOR');

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'registro', 'tothom'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'registro', 'RWE_USUARI'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'helpdesk', 'tothom'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'helpdesk', 'ZPE_HELPDESK'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'auto', 'RDS_AUTO'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'auto', 'BTE_AUTO'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'auto', 'ZPE_AUTO'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'auto', 'RTE_AUTO'); 
INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'auto', 'MOB_AUTO'); 

INSERT INTO SC_WL_USUGRU ( UGR_CODUSU, UGR_CODGRU ) VALUES ( 
'demo', 'tothom'); 

COMMIT;








	


