ALTER TABLE STR_TRAVER ADD (TRV_CONWSV  VARCHAR2(10 BYTE));
update str_traver set trv_conwsv = 'v1' where trv_contip = 'W';
ALTER TABLE STR_DOMIN ADD (DOM_WSVER  VARCHAR2(10 BYTE));
update str_domin set dom_wsver = 'v1' where dom_tipo = 'W';

commit;

ALTER TABLE STR_TRAMIT MODIFY TRA_IDENTI VARCHAR2(20);
ALTER TABLE STR_DOMIN MODIFY DOM_IDENTI VARCHAR2(20);
ALTER TABLE STR_DOCUM MODIFY DOC_MODELO VARCHAR2(20);