package es.caib.bantel.ws.v1.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Jul 23 13:31:13 CEST 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:bantel:ws:v1:services", name = "BackofficeFacade")
@XmlSeeAlso({es.caib.bantel.ws.v1.model.ObjectFactory.class})
public interface BackofficeFacade {

    @ResponseWrapper(localName = "establecerResultadoProcesoResponse", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "es.caib.bantel.ws.v1.model.EstablecerResultadoProcesoResponse")
    @RequestWrapper(localName = "establecerResultadoProceso", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "es.caib.bantel.ws.v1.model.EstablecerResultadoProceso")
    @WebMethod
    public void establecerResultadoProceso(
        @WebParam(name = "numeroEntrada", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        es.caib.bantel.ws.v1.model.ReferenciaEntrada numeroEntrada,
        @WebParam(name = "resultado", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        java.lang.String resultado,
        @WebParam(name = "resultadoProcesamiento", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        java.lang.String resultadoProcesamiento
    ) throws BackofficeFacadeException;

    @ResponseWrapper(localName = "obtenerEntradaResponse", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "es.caib.bantel.ws.v1.model.ObtenerEntradaResponse")
    @RequestWrapper(localName = "obtenerEntrada", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "es.caib.bantel.ws.v1.model.ObtenerEntrada")
    @WebResult(name = "obtenerEntradaReturn", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
    @WebMethod
    public es.caib.bantel.ws.v1.model.TramiteBTE obtenerEntrada(
        @WebParam(name = "numeroEntrada", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        es.caib.bantel.ws.v1.model.ReferenciaEntrada numeroEntrada
    ) throws BackofficeFacadeException;

    @ResponseWrapper(localName = "obtenerNumerosEntradasResponse", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "es.caib.bantel.ws.v1.model.ObtenerNumerosEntradasResponse")
    @RequestWrapper(localName = "obtenerNumerosEntradas", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "es.caib.bantel.ws.v1.model.ObtenerNumerosEntradas")
    @WebResult(name = "obtenerNumerosEntradasReturn", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
    @WebMethod
    public es.caib.bantel.ws.v1.model.ReferenciasEntrada obtenerNumerosEntradas(
        @WebParam(name = "identificadorTramite", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        java.lang.String identificadorTramite,
        @WebParam(name = "procesada", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        java.lang.String procesada,
        @WebParam(name = "desde", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        javax.xml.datatype.XMLGregorianCalendar desde,
        @WebParam(name = "hasta", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        javax.xml.datatype.XMLGregorianCalendar hasta
    ) throws BackofficeFacadeException;
}
