package es.caib.redose.model;
// Generated 07-mar-2006 18:19:34 by Hibernate Tools 3.1.0 beta3




/**
 * Firma generated by hbm2java
 */

public class Firma  implements java.io.Serializable {


    // Fields    

     private Long codigo;
     private Documento documento;
     private byte[] firma;
     private String formato;     


    // Constructors

    /** default constructor */
    public Firma() {
    }

	/** minimal constructor */
    public Firma(Long firCodigo, byte[] firFirma) {
        this.codigo = firCodigo;
        this.firma = firFirma;
    }
    
    /** full constructor */
    public Firma(Long firCodigo, Documento redoseDocum, byte[] firFirma) {
        this.codigo = firCodigo;
        this.documento = redoseDocum;
        this.firma = firFirma;
    }
    

   
    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long firCodigo) {
        this.codigo = firCodigo;
    }

    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento redoseDocum) {
        this.documento = redoseDocum;
    }

    public byte[] getFirma() {
        return this.firma;
    }
    
    public void setFirma(byte[] firFirma) {
        this.firma = firFirma;
    }

    public String getFormato() {
		return formato;
	}

    public void setFormato(String formatoFirma) {
		this.formato = formatoFirma;
	}
   








}
