package es.caib.redose.model;
// Generated 07-mar-2006 18:19:34 by Hibernate Tools 3.1.0 beta3

import java.sql.Timestamp;


/**
 * LogOperacion generated by hbm2java
 */

public class LogOperacion  implements java.io.Serializable {


    // Fields    

     private Long codigo;
     private TipoOperacion tipoOperacion;
     private String usuarioSeycon;
     private String descripcionOperacion;
     private Timestamp fecha;


    // Constructors

    /** default constructor */
    public LogOperacion() {
    }

	/** minimal constructor */
    public LogOperacion(Long logCodigo, String logDesope, Timestamp logFecha) {
        this.codigo = logCodigo;
        this.descripcionOperacion = logDesope;
        this.fecha = logFecha;
    }
    
    /** full constructor */
    public LogOperacion(Long logCodigo, TipoOperacion redoseTioper, String usuarioSeycon, String logDesope, Timestamp logFecha) {
        this.codigo = logCodigo;
        this.tipoOperacion = redoseTioper;
        this.usuarioSeycon = usuarioSeycon;
        this.descripcionOperacion = logDesope;
        this.fecha = logFecha;
    }
    

   
    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long logCodigo) {
        this.codigo = logCodigo;
    }

    public TipoOperacion getTipoOperacion() {
        return this.tipoOperacion;
    }
    
    public void setTipoOperacion(TipoOperacion redoseTioper) {
        this.tipoOperacion = redoseTioper;
    }

    public String getDescripcionOperacion() {
        return this.descripcionOperacion;
    }
    
    public void setDescripcionOperacion(String logDesope) {
        this.descripcionOperacion = logDesope;
    }

    public Timestamp getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Timestamp logFecha) {
        this.fecha = logFecha;
    }

	public String getUsuarioSeycon() {
		return usuarioSeycon;
	}

	public void setUsuarioSeycon(String usuarioSeycon) {
		this.usuarioSeycon = usuarioSeycon;
	}
   








}
