package es.caib.redose.model;
// Generated 07-mar-2006 18:09:27 by Hibernate Tools 3.1.0 beta3

import java.util.Set ;
import java.util.HashSet;

/**
 * Modelo generated by hbm2java
 */

public class Modelo  implements java.io.Serializable {


    // Fields    

     private Long codigo;
     private String modelo;
     private String nombre;
     private String descripcion;
     private char estructurado;
     private char custodiar;
     private Set versiones = new HashSet();


    // Constructors

    /** default constructor */
    public Modelo() {
    }

    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long modCodi) {
        this.codigo = modCodi;
    }

    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modModelo) {
        this.modelo = modModelo;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String modNombre) {
        this.nombre = modNombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String modDesc) {
        this.descripcion = modDesc;
    }

    public Set getVersiones() {
        return this.versiones;
    }
    
    public void setVersiones(Set redoseVerses) {
        this.versiones = redoseVerses;
    }
   
    public void addVersion(Version version){
    	version.setModelo(this);
    	versiones.add(version);
    }
    
    public void removeVersion(Version version){    	
    	versiones.remove(version);    	    
    }

	public char getEstructurado() {
		return estructurado;
	}

	public void setEstructurado(char estructurado) {
		this.estructurado = estructurado;
	}
    
	public char getCustodiar() {
		return custodiar;
	}

	public void setCustodiar(char custodiar) {
		this.custodiar = custodiar;
	}
    
}
