package es.caib.redose.model;
// Generated 07-mar-2006 18:19:33 by Hibernate Tools 3.1.0 beta3

/**
 * TipoUso generated by hbm2java
 */

public class TipoUso  implements java.io.Serializable {


    // Fields    

     private String codigo;
     private String nombre;


    // Constructors

    /** default constructor */
    public TipoUso() {
    }

    // Property accessors

    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String tiuCodi) {
        this.codigo = tiuCodi;
    }


    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String tiuNombre) {
        this.nombre = tiuNombre;
    }   








}
