package es.caib.redose.model;
// Generated 07-mar-2006 18:19:34 by Hibernate Tools 3.1.0 beta3


/**
 * TipoOperacion generated by hbm2java
 */

public class TipoOperacion  implements java.io.Serializable {


    // Fields    

     private String codigo;
     private String nombre;


    // Constructors

    /** default constructor */
    public TipoOperacion() {
    }

   
    // Property accessors

    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String topCodigo) {
        this.codigo = topCodigo;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String topNombre) {
        this.nombre = topNombre;
    }
   








}
