//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.23 at 09:16:32 AM CEST 
//


package es.caib.xml.oficioremision.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DESCRIPCION_TRAMITE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IDENTIFICADOR_TRAMITE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VERSION_TRAMITE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}PARAMETROS_TRAMITE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "descripciontramite",
    "identificadortramite",
    "versiontramite",
    "parametrostramite"
})
@XmlRootElement(name = "TRAMITE_SUBSANACION")
public class TRAMITESUBSANACION {

    @XmlElement(name = "DESCRIPCION_TRAMITE", required = true)
    protected String descripciontramite;
    @XmlElement(name = "IDENTIFICADOR_TRAMITE", required = true)
    protected String identificadortramite;
    @XmlElement(name = "VERSION_TRAMITE")
    protected int versiontramite;
    @XmlElement(name = "PARAMETROS_TRAMITE")
    protected PARAMETROSTRAMITE parametrostramite;

    /**
     * Gets the value of the descripciontramite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPCIONTRAMITE() {
        return descripciontramite;
    }

    /**
     * Sets the value of the descripciontramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPCIONTRAMITE(String value) {
        this.descripciontramite = value;
    }

    /**
     * Gets the value of the identificadortramite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDENTIFICADORTRAMITE() {
        return identificadortramite;
    }

    /**
     * Sets the value of the identificadortramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDENTIFICADORTRAMITE(String value) {
        this.identificadortramite = value;
    }

    /**
     * Gets the value of the versiontramite property.
     * 
     */
    public int getVERSIONTRAMITE() {
        return versiontramite;
    }

    /**
     * Sets the value of the versiontramite property.
     * 
     */
    public void setVERSIONTRAMITE(int value) {
        this.versiontramite = value;
    }

    /**
     * Gets the value of the parametrostramite property.
     * 
     * @return
     *     possible object is
     *     {@link PARAMETROSTRAMITE }
     *     
     */
    public PARAMETROSTRAMITE getPARAMETROSTRAMITE() {
        return parametrostramite;
    }

    /**
     * Sets the value of the parametrostramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARAMETROSTRAMITE }
     *     
     */
    public void setPARAMETROSTRAMITE(PARAMETROSTRAMITE value) {
        this.parametrostramite = value;
    }

}
