ALTER table BTE_PROAPL  ADD  TAP_REGOFI           VARCHAR2(25);
ALTER table BTE_PROAPL  ADD TAP_REGORG           VARCHAR2(25);
ALTER table BTE_PROAPL  ADD  TAP_CLAVE            VARCHAR2(1)  default 'N' not null;

comment on column BTE_PROAPL.TAP_REGOFI is
'OFICINA REGISTRO (DEFECTO GESTION EXPEDIENTES)';

comment on column BTE_PROAPL.TAP_REGORG is
'ORGANO DESTINO REGISTRO  (DEFECTO GESTION EXPEDIENTES)';

comment on column BTE_PROAPL.TAP_CLAVE is
'SI POR DEFECTO SE PERMITE EL ACCESO POR CLAVE EN NOTIFICACIONES';