package es.caib.mobtratel.ws.v1.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Jul 23 13:35:18 CEST 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:mobtratel:ws:v1:services", name = "BackofficeFacade")
@XmlSeeAlso({es.caib.mobtratel.ws.v1.model.ObjectFactory.class})
public interface BackofficeFacade {

    @ResponseWrapper(localName = "enviarMensajeResponse", targetNamespace = "urn:es:caib:mobtratel:ws:v1:model:BackofficeFacade", className = "es.caib.mobtratel.ws.v1.model.EnviarMensajeResponse")
    @RequestWrapper(localName = "enviarMensaje", targetNamespace = "urn:es:caib:mobtratel:ws:v1:model:BackofficeFacade", className = "es.caib.mobtratel.ws.v1.model.EnviarMensaje")
    @WebResult(name = "obtenerNumerosEntradasReturn", targetNamespace = "urn:es:caib:mobtratel:ws:v1:model:BackofficeFacade")
    @WebMethod
    public java.lang.String enviarMensaje(
        @WebParam(name = "mensaje", targetNamespace = "urn:es:caib:mobtratel:ws:v1:model:BackofficeFacade")
        es.caib.mobtratel.ws.v1.model.MensajeEnvio mensaje
    ) throws BackofficeFacadeException;
}
