
package es.caib.sistra.wsClient.v1.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.2
 * Tue Jul 21 10:37:14 CEST 2009
 * Generated source version: 2.2.2
 * 
 */

@WebFault(name = "fault", targetNamespace = "urn:es:caib:sistra:ws:v1:model:SistraFacade")
public class SistraFacadeException extends Exception {
    public static final long serialVersionUID = 20090721103714L;
    
    private es.caib.sistra.wsClient.v1.model.SistraFacadeException fault;

    public SistraFacadeException() {
        super();
    }
    
    public SistraFacadeException(String message) {
        super(message);
    }
    
    public SistraFacadeException(String message, Throwable cause) {
        super(message, cause);
    }

    public SistraFacadeException(String message, es.caib.sistra.wsClient.v1.model.SistraFacadeException fault) {
        super(message);
        this.fault = fault;
    }

    public SistraFacadeException(String message, es.caib.sistra.wsClient.v1.model.SistraFacadeException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public es.caib.sistra.wsClient.v1.model.SistraFacadeException getFaultInfo() {
        return this.fault;
    }
}
