//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.07 at 08:58:59 AM CEST 
//


package es.caib.xml.taxa.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LOCALIZADOR" minOccurs="0"/>
 *         &lt;element ref="{}MODELO"/>
 *         &lt;element ref="{}IDTAXA"/>
 *         &lt;choice>
 *           &lt;element ref="{}SUBCONCEPTE" minOccurs="0"/>
 *           &lt;sequence>
 *             &lt;element ref="{}IMPORT"/>
 *             &lt;element ref="{}CONCEPTE"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{}DECLARANT"/>
 *       &lt;/sequence>
 *       &lt;attribute name="versio" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="accio" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="imprimir"/>
 *             &lt;enumeration value="pagar"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localizador",
    "modelo",
    "idtaxa",
    "subconcepte",
    "_import",
    "concepte",
    "declarant"
})
@XmlRootElement(name = "TAXA")
public class TAXA {

    @XmlElement(name = "LOCALIZADOR")
    protected String localizador;
    @XmlElement(name = "MODELO", required = true)
    protected String modelo;
    @XmlElement(name = "IDTAXA", required = true)
    protected IDTAXA idtaxa;
    @XmlElement(name = "SUBCONCEPTE")
    protected SUBCONCEPTE subconcepte;
    @XmlElement(name = "IMPORT")
    protected IMPORT _import;
    @XmlElement(name = "CONCEPTE")
    protected CONCEPTE concepte;
    @XmlElement(name = "DECLARANT", required = true)
    protected DECLARANT declarant;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String versio;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String accio;

    /**
     * Gets the value of the localizador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALIZADOR() {
        return localizador;
    }

    /**
     * Sets the value of the localizador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALIZADOR(String value) {
        this.localizador = value;
    }

    /**
     * Gets the value of the modelo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMODELO() {
        return modelo;
    }

    /**
     * Sets the value of the modelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMODELO(String value) {
        this.modelo = value;
    }

    /**
     * Gets the value of the idtaxa property.
     * 
     * @return
     *     possible object is
     *     {@link IDTAXA }
     *     
     */
    public IDTAXA getIDTAXA() {
        return idtaxa;
    }

    /**
     * Sets the value of the idtaxa property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDTAXA }
     *     
     */
    public void setIDTAXA(IDTAXA value) {
        this.idtaxa = value;
    }

    /**
     * Gets the value of the subconcepte property.
     * 
     * @return
     *     possible object is
     *     {@link SUBCONCEPTE }
     *     
     */
    public SUBCONCEPTE getSUBCONCEPTE() {
        return subconcepte;
    }

    /**
     * Sets the value of the subconcepte property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUBCONCEPTE }
     *     
     */
    public void setSUBCONCEPTE(SUBCONCEPTE value) {
        this.subconcepte = value;
    }

    /**
     * Gets the value of the import property.
     * 
     * @return
     *     possible object is
     *     {@link IMPORT }
     *     
     */
    public IMPORT getIMPORT() {
        return _import;
    }

    /**
     * Sets the value of the import property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMPORT }
     *     
     */
    public void setIMPORT(IMPORT value) {
        this._import = value;
    }

    /**
     * Gets the value of the concepte property.
     * 
     * @return
     *     possible object is
     *     {@link CONCEPTE }
     *     
     */
    public CONCEPTE getCONCEPTE() {
        return concepte;
    }

    /**
     * Sets the value of the concepte property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONCEPTE }
     *     
     */
    public void setCONCEPTE(CONCEPTE value) {
        this.concepte = value;
    }

    /**
     * Gets the value of the declarant property.
     * 
     * @return
     *     possible object is
     *     {@link DECLARANT }
     *     
     */
    public DECLARANT getDECLARANT() {
        return declarant;
    }

    /**
     * Sets the value of the declarant property.
     * 
     * @param value
     *     allowed object is
     *     {@link DECLARANT }
     *     
     */
    public void setDECLARANT(DECLARANT value) {
        this.declarant = value;
    }

    /**
     * Gets the value of the versio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersio() {
        return versio;
    }

    /**
     * Sets the value of the versio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersio(String value) {
        this.versio = value;
    }

    /**
     * Gets the value of the accio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccio() {
        return accio;
    }

    /**
     * Sets the value of the accio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccio(String value) {
        this.accio = value;
    }

}
