INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
512, 'OMN', 'Omán', 'Oman', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
528, 'NLD', 'Países Bajos', 'Països Baixos', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
586, 'PAK', 'Pakistán', 'Pakistan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
585, 'PLW', 'Palau', 'Palau', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
275, 'PSE', 'Palestina', 'Palestina; Cisjordània i Gaza', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
591, 'PAN', 'Panamá', 'Panamà', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
598, 'PNG', 'Papúa Nueva Guinea', 'Papua Nova Guinea', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
600, 'PRY', 'Paraguay', 'Paraguai', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
604, 'PER', 'Perú', 'Perú', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
612, 'PCN', 'Islas Pitcairn', 'Pitcairn, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
258, 'PYF', 'Polinesia Francesa', 'Polinèsia Francesa', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
616, 'POL', 'Polonia', 'Polònia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
620, 'PRT', 'Portugal', 'Portugal', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
630, 'PRI', 'Puerto Rico', 'Puerto Rico', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
634, 'QAT', 'Qatar', 'Qatar', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
826, 'GBR', 'Reino Unido', 'Regne Unit; Gran Bretanya', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
638, 'REU', 'Reunión', 'Reunió, illa de la', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
642, 'ROU', 'Rumania', 'Romania', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
643, 'RUS', 'Rusia', 'Rússia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
646, 'RWA', 'Ruanda', 'Rwanda', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
732, 'ESH', 'Sahara Occidental', 'Sàhara Occidental', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
659, 'KNA', 'San Cristóbal y Nevis', 'Saint Kitts i Nevis', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
662, 'LCA', 'Santa Lucía', 'Saint Lucia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
666, 'SPM', 'San Pedro y Miquel¢n', 'Saint-Pierre i Miquelon', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
90, 'SLB', 'Islas Salomón', 'Salomó', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
222, 'SLV', 'El Salvador', 'Salvador, El', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
882, 'WSM', 'Samoa', 'Samoa', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
16, 'ASM', 'Samoa Americana', 'Samoa Nord-americana', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
674, 'SMR', 'San Marino', 'San Marino', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
654, 'SHN', 'Santa Helena', 'Santa Helena', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
678, 'STP', 'Santo Tomé y Príncipe', 'Sao Tomé i Príncipe', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
686, 'SEN', 'Senegal', 'Senegal', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
891, 'SCG', 'Serbia y Montenegro', 'Sèrbia i Montenegro', 'N', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
690, 'SYC', 'Seychelles', 'Seychelles', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
694, 'SLE', 'Sierra Leona', 'Sierra Leone', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
702, 'SGP', 'Singapur', 'Singapur', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
760, 'SYR', 'Siria', 'Síria', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
706, 'SOM', 'Somalia', 'Somàlia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
242, 'FJI', 'Fiyi', 'Fiji', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
608, 'PHL', 'Filipinas', 'Filipines', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
246, 'FIN', 'Finlandia', 'Finlàndia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
144, 'LKA', 'Sri Lanka', 'Sri Lanka', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
710, 'ZAF', 'Sudáfrica', 'Sud-àfrica', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
736, 'SDN', 'Sudán', 'Sudan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
752, 'SWE', 'Suecia', 'Suècia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
756, 'CHE', 'Suiza', 'Suïssa', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
740, 'SUR', 'Surinam', 'Surinam', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
744, 'SJM', 'Svalbard y Jan Mayen', 'Svalbard i Jan Mayen', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
748, 'SWZ', 'Suazilandia', 'Swazilàndia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
762, 'TJK', 'Tayikistán', 'Tadjikistan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
764, 'THA', 'Tailandia', 'Tailàndia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
158, 'TWN', 'Taiwán', 'Taiwan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
834, 'TZA', 'Tanzania', 'Tanzània', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
260, 'ATF', 'Territorios Australes Franceses', 'Territoris Francesos del Sud', 'S'
, NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
626, 'TLS', 'Timor Oriental', 'Timor Oriental', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
768, 'TGO', 'Togo', 'Togo', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
772, 'TKL', 'Tokelau', 'Tokelau', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
776, 'TON', 'Tonga', 'Tonga', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
780, 'TTO', 'Trinidad y Tobago', 'Trinitat i Tobago', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
788, 'TUN', 'Túnez', 'Tunísia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
795, 'TKM', 'Turkmenistán', 'Turkmenistan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
796, 'TCA', 'Islas Turcas y Caicos', 'Turks i Caicos, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
792, 'TUR', 'Turquía', 'Turquia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
798, 'TUV', 'Tuvalu', 'Tuvalu', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
148, 'TCD', 'Chad', 'Txad', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
203, 'CZE', 'República Checa', 'Txeca, República', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
804, 'UKR', 'Ucrania', 'Ucraïna', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
800, 'UGA', 'Uganda', 'Uganda', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
858, 'URY', 'Uruguay', 'Uruguai', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
860, 'UZB', 'Uzbekistán', 'Uzbekistan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
548, 'VUT', 'Vanuatu', 'Vanuatu', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
336, 'VAT', 'Ciudad del Vaticano', 'Vaticà, Ciutat del', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
862, 'VEN', 'Venezuela', 'Veneçuela', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
92, 'VGB', 'Islas Vírgenes Británicas', 'Verges Britàniques, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
850, 'VIR', 'Islas Vírgenes de los Estados Unidos', 'Verges Nord-americanes, illes'
, 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
704, 'VNM', 'Vietnam', 'Vietnam', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
876, 'WLF', 'Wallis y Futuna', 'Wallis i Futuna', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
152, 'CHL', 'Chile', 'Xile', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
156, 'CHN', 'China', 'Xina', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
196, 'CYP', 'Chipre', 'Xipre', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
894, 'ZMB', 'Zambia', 'Zàmbia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
716, 'ZWE', 'Zimbabue', 'Zimbabwe', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
688, 'RSB', 'Serbia', 'Sèrbia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
499, 'MNE', 'Montenegro', 'Montenegro', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
408, 'PRK', 'Corea del Norte', 'Corea del Nord', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
670, 'VCT', 'San Vicente y las Granadinas', 'Saint Vincent i les Grenadines', 'S'
, NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
384, 'CIV', 'Costa de Marfil', 'Costa d''Ivori', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
4, 'AFG', 'Afganistán', 'Afganistan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
250, 'FRA', 'Francia', 'França', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
266, 'GAB', 'Gabón', 'Gabon', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
270, 'GMB', 'Gambia', 'Gàmbia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
268, 'GEO', 'Georgia', 'Geòrgia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
239, 'SGS', 'Islas Georgias del Sur y Sandwich del Sur', 'Geòrgia del Sud i Sandwich del Sud, illes'
, 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
288, 'GHA', 'Ghana', 'Ghana', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
292, 'GIB', 'Gibraltar', 'Gibraltar', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
300, 'GRC', 'Grecia', 'Grècia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
308, 'GRD', 'Granada', 'Grenada', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
304, 'GRL', 'Groenlandia', 'Grenlàndia; Groenlàndia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
312, 'GLP', 'Guadalupe', 'Guadeloupe', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
254, 'GUF', 'Guayana Francesa', 'Guaiana Francesa', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
316, 'GUM', 'Guam', 'Guam', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
320, 'GTM', 'Guatemala', 'Guatemala', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
324, 'GIN', 'Guinea', 'Guinea', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
624, 'GNB', 'Guinea-Bissau', 'Guinea Bissau', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
226, 'GNQ', 'Guinea Ecuatorial', 'Guinea Equatorial', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
328, 'GUY', 'Guayana', 'Guyana', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
332, 'HTI', 'Haití', 'Haití', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
334, 'HMD', 'Islas Heard y McDonald', 'Heard, illa i McDonald, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
340, 'HND', 'Honduras', 'Hondures', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
344, 'HKG', 'Hong Kong', 'Hong Kong', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
348, 'HUN', 'Hungría', 'Hongria', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
887, 'YEM', 'Yemen', 'Iemen', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
581, 'UMI', 'Islas ultramarinas de Estados Unidos', 'Illes Perifèriques Menors dels EUA'
, 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
356, 'IND', 'India', 'Índia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
360, 'IDN', 'Indonesia', 'Indonèsia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
364, 'IRN', 'Irán', 'Iran', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
368, 'IRQ', 'Iraq', 'Iraq', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
372, 'IRL', 'Irlanda', 'Irlanda', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
352, 'ISL', 'Islandia', 'Islàndia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
376, 'ISR', 'Israel', 'Israel', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
380, 'ITA', 'Iraq', 'Itàlia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
248, 'ALA', 'Islas Aland', 'Aland, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
8, 'ALB', 'Albania', 'Albània', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
276, 'DEU', 'Alemania', 'Alemanya', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
12, 'DZA', 'Argelia', 'Algèria', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
20, 'AND', 'Andorra', 'Andorra', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
24, 'AGO', 'Angola', 'Angola', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
660, 'AIA', 'Anguilla', 'Anguilla', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
10, 'ATA', 'Antártida', 'Antàrtida', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
28, 'ATG', 'Antigua y Barbuda', 'Antigua i Barbuda', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
530, 'ANT', 'Antillas Neerlandesas', 'Antilles Holandeses', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
682, 'SAU', 'Arabia Saudita', 'Aràbia Saudita', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
32, 'ARG', 'Argentina', 'Argentina', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
51, 'ARM', 'Armenia', 'Armènia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
533, 'ABW', 'Aruba', 'Aruba', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
36, 'AUS', 'Australia', 'Austràlia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
40, 'AUT', 'Austria', 'Àustria', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
31, 'AZE', 'Azerbaiyán', 'Azerbaidjan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
44, 'BHS', 'Bahamas', 'Bahames', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
48, 'BHR', 'Bahréin', 'Bahrain', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
50, 'BGD', 'Bangladesh', 'Bangla Desh', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
52, 'BRB', 'Barbados', 'Barbados', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
56, 'BEL', 'Bélgica', 'Bèlgica', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
84, 'BLZ', 'Belice', 'Belize', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
204, 'BEN', 'Benin', 'Benín', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
60, 'BMU', 'Bermudas', 'Bermudes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
64, 'BTN', 'Bhután', 'Bhutan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
112, 'BLR', 'Bielorrusia', 'Bielorússia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
68, 'BOL', 'Bolivia', 'Bolívia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
70, 'BIH', 'Bosnia-Herzegovina', 'Bòsnia i Hercegovina', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
72, 'BWA', 'Botsuana', 'Botswana', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
74, 'BVT', 'Isla Bouvet', 'Bouvet, illa', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
76, 'BRA', 'Brasil', 'Brasil', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
96, 'BRN', 'Brunei', 'Brunei', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
100, 'BGR', 'Bulgaria', 'Bulgària', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
854, 'BFA', 'Burkina Faso', 'Burkina Faso', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
108, 'BDI', 'Burundi', 'Burundi', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
136, 'CYM', 'Islas Caimán', 'Caiman, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
116, 'KHM', 'Camboya', 'Cambodja', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
120, 'CMR', 'Camerún', 'Camerun', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
124, 'CAN', 'Canadá', 'Canadà', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
132, 'CPV', 'Cabo Verde', 'Cap Verd', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
140, 'CAF', 'República Centroafricana', 'Centreafricana, República', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
162, 'CXR', 'Isla de Navidad', 'Christmas, illa', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
166, 'CCK', 'Islas Cocos', 'Cocos, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
170, 'COL', 'Colombia', 'Colúmbia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
174, 'COM', 'Comoras', 'Comores', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
178, 'COG', 'República del Congo', 'Congo, República del', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
180, 'COD', 'República Democrática del Congo', 'Congo, República Democràtica del'
, 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
184, 'COK', 'Islas Cook', 'Cook, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
410, 'KOR', 'Corea del Sur', 'Corea del Sud; Corea, República de', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
188, 'CRI', 'Costa Rica', 'Costa Rica', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
191, 'HRV', 'Croacia', 'Croàcia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
192, 'CUB', 'Cuba', 'Cuba', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
208, 'DNK', 'Dinamarca', 'Dinamarca', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
262, 'DJI', 'Yibuti', 'Djibouti', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
212, 'DMA', 'Dominica', 'Dominica', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
214, 'DOM', 'República Dominicana', 'Dominicana, República', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
818, 'EGY', 'Egipto', 'Egipte', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
218, 'ECU', 'Ecuador', 'Equador', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
784, 'ARE', 'Emiratos µrabes Unidos', 'Emirats Àrabs Units', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
232, 'ERI', 'Eritrea', 'Eritrea', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
703, 'SVK', 'Eslovaquia', 'Eslovàquia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
705, 'SVN', 'Eslovenia', 'Eslovènia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
724, 'ESP', 'España', 'Espanya', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
840, 'USA', 'Estados Unidos', 'Estats Units (EUA)', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
233, 'EST', 'Estonia', 'Estònia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
231, 'ETH', 'Etiopía', 'Etiòpia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
234, 'FRO', 'Islas Feroe', 'Fèroe, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
388, 'JAM', 'Jamaica', 'Jamaica', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
392, 'JPN', 'Japón', 'Japó', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
400, 'JOR', 'Jordania', 'Jordània', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
398, 'KAZ', 'Kazajstán', 'Kazakhstan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
404, 'KEN', 'Kenia', 'Kenya', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
417, 'KGZ', 'Kirguistán', 'Kirguizistan', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
296, 'KIR', 'Kiribati', 'Kiribati', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
414, 'KWT', 'Kuwait', 'Kuwait', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
418, 'LAO', 'Laos', 'Laos', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
426, 'LSO', 'Lesotho', 'Lesotho', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
428, 'LVA', 'Letonia', 'Letònia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
422, 'LBN', 'Líbano', 'Líban', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
430, 'LBR', 'Liberia', 'Libèria', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
434, 'LBY', 'Libia', 'Líbia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
438, 'LIE', 'Liechtenstein', 'Liechtenstein', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
440, 'LTU', 'Lituania', 'Lituània', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
442, 'LUX', 'Luxemburgo', 'Luxemburg', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
446, 'MAC', 'Macao', 'Macau', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
807, 'MKD', 'ARY Macedonia', 'Macedònia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
450, 'MDG', 'Madagascar', 'Madagascar', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
458, 'MYS', 'Malasia', 'Malàisia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
454, 'MWI', 'Malawi', 'Malawi', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
462, 'MDV', 'Maldivas', 'Maldives', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
466, 'MLI', 'Malí', 'Mali', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
470, 'MLT', 'Malta', 'Malta', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
238, 'FLK', 'Islas Malvinas', 'Malvines, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
580, 'MNP', 'Islas Marianas del Norte', 'Mariannes Septentrionals, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
504, 'MAR', 'Marruecos', 'Marroc', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
584, 'MHL', 'Islas Marshall', 'Marshall, illes', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
474, 'MTQ', 'Martinica', 'Martinica', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
480, 'MUS', 'Mauricio', 'Maurici', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
478, 'MRT', 'Mauritania', 'Mauritània', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
175, 'MYT', 'Mayotte', 'Mayotte', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
484, 'MEX', 'México', 'Mèxic', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
583, 'FSM', 'Micronesia', 'Micronèsia, Estats Federats de', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
508, 'MOZ', 'Mozambique', 'Moçambic', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
498, 'MDA', 'Moldavia', 'Moldàvia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
492, 'MCO', 'Mónaco', 'Mònaco', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
496, 'MNG', 'Mongolia', 'Mongòlia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
500, 'MSR', 'Montserrat', 'Montserrat', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
104, 'MMR', 'Myanmar', 'Myanmar', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
516, 'NAM', 'Namibia', 'Namíbia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
520, 'NRU', 'Nauru', 'Nauru', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
524, 'NPL', 'Nepal', 'Nepal', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
558, 'NIC', 'Nicaragua', 'Nicaragua', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
562, 'NER', 'Níger', 'Níger', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
566, 'NGA', 'Nigeria', 'Nigèria', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
570, 'NIU', 'Niue', 'Niue', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
574, 'NFK', 'Isla Norfolk', 'Norfolk, illa', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
578, 'NOR', 'Noruega', 'Noruega', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
540, 'NCL', 'Nueva Caledonia', 'Nova Caledònia', 'S', NULL); 
INSERT INTO STR_DPAIS ( PAI_CODIGO, PAI_CODALF, PAI_DENCAS, PAI_DENCAT, PAI_VIGENC,
PAI_COD2AF ) VALUES ( 
554, 'NZL', 'Nueva Zelanda', 'Nova Zelanda', 'S', NULL); 
commit;
 
