INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
1, 16, 'ALAVA', 'Àlaba'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
2, 8, 'ALBACETE', 'Albacete'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
3, 10, 'ALICANTE', 'Alacant'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
4, 1, 'ALMERÍA', 'Almeria'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
5, 7, 'AVILA', 'Àvila'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
6, 11, 'BADAJOZ', 'Badajoz'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
7, 4, 'Balears (Illes)', 'Balears (Illes)'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
8, 9, 'BARCELONA', 'Barcelona'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
9, 7, 'BURGOS', 'Burgos'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
10, 11, 'CÁCERES', 'Càceres'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
11, 1, 'CÁDIZ', 'Cadis'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
12, 10, 'CASTELLÓN', 'Castelló'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
13, 8, 'CIUDAD REAL', 'Ciudad Real'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
14, 1, 'CÓRDOBA', 'Còrdova'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
15, 12, 'CORUÑA (A)', 'Corunya (La)'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
16, 8, 'CUENCA', 'Conca'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
17, 9, 'GERONA', 'Girona'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
18, 1, 'GRANADA', 'Granada'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
19, 8, 'GUADALAJARA', 'Guadalajara'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
20, 16, 'GUIPÚZCOA', 'Guipúscoa'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
21, 1, 'HUELVA', 'Huelva'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
22, 2, 'HUESCA', 'Osca'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
23, 1, 'JAÉN', 'Jaén'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
24, 7, 'LEÓN', 'Lleó'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
25, 9, 'LÉRIDA', 'Lleida'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
26, 17, 'RIOJA (LA)', 'Rioja (La)'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
27, 12, 'LUGO', 'Lugo'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
28, 13, 'MADRID', 'Madrid'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
29, 1, 'MÁLAGA', 'Màlaga'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
30, 14, 'MURCIA', 'Múrcia'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
31, 15, 'NAVARRA', 'Navarra'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
32, 12, 'ORENSE', 'Orense'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
33, 3, 'ASTURIAS', 'Astúries'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
34, 7, 'PALENCIA', 'Palència'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
35, 5, 'PALMAS (LAS)', 'Palmas (Las)'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
36, 12, 'PONTEVEDRA', 'Pontevedra'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
37, 7, 'SALAMANCA', 'Salamanca'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
38, 5, 'SANTA CRUZ DE TENERIFE', 'Tenerife'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
39, 6, 'CANTABRIA', 'Cantàbria'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
40, 7, 'SEGOVIA', 'Segòvia'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
41, 1, 'SEVILLA', 'Sevilla'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
42, 7, 'SORIA', 'Sòria'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
43, 9, 'TARRAGONA', 'Tarragona'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
44, 2, 'TERUEL', 'Terol'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
45, 8, 'TOLEDO', 'Toledo'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
46, 10, 'VALENCIA', 'València'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
47, 7, 'VALLADOLID', 'Valladolid'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
48, 16, 'VIZCAYA', 'Biscaia'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
49, 7, 'ZAMORA', 'Zamora'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
50, 2, 'ZARAGOZA', 'Saragossa'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
51, 18, 'CEUTA', 'Ceuta'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
52, 19, 'MELILLA', 'Melilla'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
99, 99, 'N/C', 'n/c'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
53, 99, 'Desconocido', 'Desconegut'); 
INSERT INTO STR_DPROVI ( PRO_CODIGO, PRO_CODCAU, PRO_DENCAS, PRO_DENCAT ) VALUES ( 
60, 99, 'EXTRANJERO', 'Estranger'); 
commit;
 
