package es.caib.sistra.model;
// Generated 21-mar-2006 11:41:41 by Hibernate Tools 3.1.0 beta3



/**
 * StrTradoc generated by hbm2java
 */

public class TraDocumento  implements Traduccion {


    // Fields    
    private String descripcion;
    private String informacion;
     
     
	public String getDescripcion() {
		return descripcion;
	}
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	public String getInformacion() {
		return informacion;
	}
	public void setInformacion(String informacion) {
		this.informacion = informacion;
	}

     
}
