package es.caib.sistra.model;
// Generated 21-mar-2006 11:41:40 by Hibernate Tools 3.1.0 beta3



/**
 * StrTramtr generated by hbm2java
 */

public class TraMensajeTramite  implements Traduccion {


    // Fields    
     private String mensaje;

	public String getMensaje() {
		return mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

}
