package es.caib.mobtratel.ws.v2.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Mon Jun 14 09:04:18 CEST 2010
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:mobtratel:ws:v2:services", name = "BackofficeFacade")
@XmlSeeAlso({es.caib.mobtratel.ws.v2.model.ObjectFactory.class})
public interface BackofficeFacade {

    @ResponseWrapper(localName = "enviarMensajeResponse", targetNamespace = "urn:es:caib:mobtratel:ws:v2:model:BackofficeFacade", className = "es.caib.mobtratel.ws.v2.model.EnviarMensajeResponse")
    @RequestWrapper(localName = "enviarMensaje", targetNamespace = "urn:es:caib:mobtratel:ws:v2:model:BackofficeFacade", className = "es.caib.mobtratel.ws.v2.model.EnviarMensaje")
    @WebResult(name = "enviarMensajeReturn", targetNamespace = "urn:es:caib:mobtratel:ws:v2:model:BackofficeFacade")
    @WebMethod
    public java.lang.String enviarMensaje(
        @WebParam(name = "mensaje", targetNamespace = "urn:es:caib:mobtratel:ws:v2:model:BackofficeFacade")
        es.caib.mobtratel.ws.v2.model.MensajeEnvio mensaje
    ) throws BackofficeFacadeException;
}
