package es.caib.redose.model;
// Generated 07-mar-2006 18:19:34 by Hibernate Tools 3.1.0 beta3

import java.util.Map;


/**
 * PlantillaTraducible generated by hbm2java
 */

public class Plantilla  extends Traducible implements java.io.Serializable {

    // Fields    

     private Long codigo;
     private Version version;
     private String tipo;
     private Formateador formateador;
     private char defecto;
     private char barcode;
     private char sello;

    // Constructors

    /** default constructor */
    public Plantilla() {
    }

	    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long plaCodig) {
        this.codigo = plaCodig;
    }

    public Version getVersion() {
        return this.version;
    }
    
    public void setVersion(Version redoseVers) {
        this.version = redoseVers;
    }

    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String plaTipo) {
        this.tipo = plaTipo;
    }

    public Map getPlantillasIdioma() {
        return this.getTraducciones();
    }
    
    public void setPlantillasIdioma(Map redosePlaidis) {
        this.setTraducciones( redosePlaidis );
    }
   
    public void addPlantillaIdioma(PlantillaIdioma plantillaIdioma){    	
    	plantillaIdioma.setPlantilla(this);
    	//this.traducciones.add(plantillaIdioma);
    	//this.traducciones.put( plantillaIdioma.getIdioma(), plantillaIdioma );
    	this.setTraduccion( plantillaIdioma.getIdioma(), plantillaIdioma );
    }
    
    public void removePlantillaIdioma(PlantillaIdioma plantillaIdioma)
    {    	
    	Map traducciones = this.getPlantillasIdioma();
    	traducciones.remove(plantillaIdioma.getIdioma());
    	this.setTraducciones( traducciones );
    }
    
    public String toString()
    {
    	StringBuffer sbReturn = new StringBuffer();
    	sbReturn.append( "Codigo plantilla: " ).append( this.getCodigo() ).append( ";" ).append( "PLANTILLA IDIOMAS: ").append( this.getPlantillasIdioma() );
    	return sbReturn.toString();
    }

	public Formateador getFormateador()
	{
		if(formateador == null){
			formateador = new Formateador();
		}
		return formateador;			
	}

	public void setFormateador(Formateador formateador)
	{
		this.formateador = formateador;
	}

	public char getDefecto() {
		return defecto;
	}

	public void setDefecto(char defecto) {
		this.defecto = defecto;
	}

	public char getBarcode() {
		return barcode;
	}

	public void setBarcode(char barcode) {
		this.barcode = barcode;
	}

	public char getSello() {
		return sello;
	}

	public void setSello(char sello) {
		this.sello = sello;
	}
}
