//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.25 at 03:10:19 PM CEST 
//


package es.caib.xml.datospropios.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}INSTRUCCIONES"/>
 *         &lt;element ref="{}SOLICITUD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instrucciones",
    "solicitud"
})
@XmlRootElement(name = "DATOS_PROPIOS")
public class DATOSPROPIOS {

    @XmlElement(name = "INSTRUCCIONES", required = true)
    protected INSTRUCCIONES instrucciones;
    @XmlElement(name = "SOLICITUD")
    protected SOLICITUD solicitud;

    /**
     * Gets the value of the instrucciones property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCCIONES }
     *     
     */
    public INSTRUCCIONES getINSTRUCCIONES() {
        return instrucciones;
    }

    /**
     * Sets the value of the instrucciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCCIONES }
     *     
     */
    public void setINSTRUCCIONES(INSTRUCCIONES value) {
        this.instrucciones = value;
    }

    /**
     * Gets the value of the solicitud property.
     * 
     * @return
     *     possible object is
     *     {@link SOLICITUD }
     *     
     */
    public SOLICITUD getSOLICITUD() {
        return solicitud;
    }

    /**
     * Sets the value of the solicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOLICITUD }
     *     
     */
    public void setSOLICITUD(SOLICITUD value) {
        this.solicitud = value;
    }

}
