CREATE TABLE SC_WL_USUARI
(
  USU_CODI    VARCHAR(200)                NOT NULL,
  USU_PASS    VARCHAR(50),
  USU_NOM     VARCHAR(50),
  USU_NIF     VARCHAR(10)
);

CREATE TABLE SC_WL_USUGRU
(
  UGR_CODUSU  VARCHAR(200),
  UGR_CODGRU  VARCHAR(50)
);

CREATE UNIQUE INDEX DNI_AK ON SC_WL_USUARI (USU_NIF);


CREATE UNIQUE INDEX USUARI_PK ON SC_WL_USUARI (USU_CODI);


ALTER TABLE SC_WL_USUARI ADD CONSTRAINT USUARI_PK_2 PRIMARY KEY (USU_CODI);
