/* IDIOMAS */
INSERT INTO STR_IDIOMA ( IDI_CODIGO, IDI_ORDEN ) VALUES ( 
'es', 1); 
INSERT INTO STR_IDIOMA ( IDI_CODIGO, IDI_ORDEN ) VALUES ( 
'ca', 2); 

/* ORGANISMO GENERICO */
INSERT INTO STR_ORGRES (ORG_CODIGO, ORG_DESC) VALUES (NEXTVAL('STR_SEQORG'),'GE-Genérico');

/* GESTOR FORMULARIO */
INSERT INTO STR_GESFRM ( GSF_IDENT, GSF_DESC, GSF_URL, GSF_URLTRA,GSF_URLRED ) 
VALUES ('forms', 'FORMS', '@sistra.url@', '@forms.server@/formfront/iniciTelematic.do', '/formfront/continuacioTelematic.do'); 

/* DOMINIOS ESTRUCTURA ORGANICA */
INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GESACARBUA', 'S', 'es.caib.sistra.db', 'select ''1'' codigo, null parent, ''Unidad Test'' descripcion from dual'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Arbol unidadades administrativas');

INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GESACUADES', 'S', 'es.caib.sistra.db', 'SELECT  ''1'' CODIGO,''Unidad Test'' DESCRIPCION  FROM dual WHERE ''XX'' <> ?'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Descripción de unidad administrativa. Parametrizado por código unidad.'); 

INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GESACUNADM', 'S', 'es.caib.sistra.db', 'SELECT  ''1'' CODIGO,''Unidad Test'' DESCRIPCION  FROM dual'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Lista de unidades administrativas'); 

/* 	DOMINIOS ESTRUCTURA RDS */
INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GERDSMODE', 'S', 'es.caib.redose.db', 'SELECT 	MOD_MODELO CODIGO,MOD_MODELO || '' - '' || MOD_NOMBRE DESCRIPCION FROM RDS_MODELO ORDER BY 1'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Lista de modelos de documentos del RDS'); 

INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GERDSVERS', 'S', 'es.caib.redose.db', 'SELECT RDS_VERS.VER_VERSIO CODIGO, TO_CHAR(RDS_VERS.VER_VERSIO) DESCRIPCION FROM RDS_VERS,RDS_MODELO WHERE RDS_MODELO.MOD_CODIGO =  RDS_VERS.VER_CODMOD AND RDS_MODELO.MOD_MODELO = ? ORDER BY 1'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Lista de versiones de un modelo de documento del RDS. Parametrizado por código modelo.'); 

/* 	DOMINIOS ESTRUCTURA FORMS */
INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GEFORMMODE', 'S', 'es.caib.rolforms.db', 'SELECT DISTINCT RFR_FORMUL.FOR_MODELO CODIGO,RFR_FORMUL.FOR_MODELO || '' - '' || RFR_TRAFOR.TRF_TITULO DESCRIPCION
FROM RFR_FORMUL,RFR_TRAFOR
WHERE RFR_TRAFOR.TRF_CODFOR = RFR_FORMUL.FOR_CODI AND RFR_TRAFOR.TRF_CODIDI = ''es''
ORDER BY 1'
, NULL, 'R', 'N', NULL, NULL, 'N', 1, 'Lista de modelos de formularios'); 

INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GEFORMMOVE', 'S', 'es.caib.rolforms.db', 'SELECT RFR_FORMUL.FOR_MODELO MODELO,
	   RFR_FORMUL.FOR_MODELO || '' - '' || RFR_TRAFOR.TRF_TITULO DESCRIPCION,
	   RFR_FORMUL.FOR_VERSIO VERSION	   	   
FROM RFR_FORMUL,RFR_TRAFOR
WHERE RFR_TRAFOR.TRF_CODFOR = RFR_FORMUL.FOR_CODI AND RFR_TRAFOR.TRF_CODIDI = ''es''
ORDER BY 1,3'
, NULL, 'R', 'N', NULL, NULL, 'N', 1, 'Arbol de formularios y versiones'); 

INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GEFORMVERS', 'S', 'es.caib.rolforms.db', 'SELECT  RFR_FORMUL.FOR_VERSIO CODIGO, RFR_FORMUL.FOR_VERSIO DESCRIPCION 
FROM RFR_FORMUL 
WHERE RFR_FORMUL.FOR_MODELO = ?
ORDER BY 1'
, NULL, 'R', 'N', NULL, NULL, 'N', 1, 'Lista de versiones de un formulario. Parametrizado por código de formulario.'); 


/* DOMINIOS INFORMACIÓN GEOGRAFICA */
INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GEPAISES', 'S', 'es.caib.sistra.db', 'SELECT TRIM( PAI_CODALF ) CODIGO, UPPER( PAI_DENCAS ) DESCRIPCION FROM STR_DPAIS WHERE PAI_VIGENC = ''S'' ORDER BY DESCRIPCION'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Lista de paises'); 

INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GEPROVINCI', 'S', 'es.caib.sistra.db', 'SELECT PRO_CODIGO CODIGO, PRO_DENCAT DESCRIPCION FROM STR_DPROVI ORDER BY CODIGO'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Lista de provincias'); 

INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GEGMUNICI', 'S', 'es.caib.sistra.db', 'SELECT MUN_CODIGO CODIGO, MUN_DENOFI DESCRIPCION FROM STR_DMUNIC WHERE MUN_PROVIN = ? ORDER BY DESCRIPCION'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Lista de municipios de una provincia. Parametrizado por código provincia.'); 

INSERT INTO STR_DOMIN ( DOM_CODIGO, DOM_IDENTI, DOM_TIPO, DOM_URL, DOM_SQL, DOM_JNDI, DOM_EJBREM,
DOM_EJBSTD, DOM_USR, DOM_PWD, DOM_CACHE, DOM_CODORG, DOM_DESC ) VALUES ( 
NEXTVAL('STR_SEQDOM'), 'GEMUNIDESC', 'S', 'es.caib.sistra.db', 'SELECT MUN_CODIGO CODIGO, MUN_DENOFI DESCRIPCION FROM STR_DMUNIC WHERE MUN_PROVIN = ? AND MUN_CODIGO = ?'
, NULL, 'L', 'N', NULL, NULL, 'N', 1, 'Descripción de un municipio. Parametrizado por código provincia y por código municipio.'); 


update STR_DOMIN  set DOM_USR = '6f80fcb1f11f76b5bf10301a1cb4c5c0' where DOM_USR IS NOT NULL;
update STR_DOMIN  set DOM_PWD = '6f80fcb1f11f76b5bf10301a1cb4c5c0' where DOM_PWD IS NOT NULL;

update STR_TRAVER  set TRV_CONUSU = '6f80fcb1f11f76b5bf10301a1cb4c5c0' where TRV_CONUSU IS NOT NULL;
update STR_TRAVER  set TRV_CONPWD = '6f80fcb1f11f76b5bf10301a1cb4c5c0' where TRV_CONPWD IS NOT NULL;

update str_traver set trv_conwsv = 'v1' where trv_contip = 'W';
update str_domin set dom_wsver = 'v1' where dom_tipo = 'W';

INSERT INTO STR_IDIOMA ( IDI_CODIGO, IDI_ORDEN ) VALUES ('en', 3); 

COMMIT;