ALTER table BTE_PROAPL ADD  TAP_PLNOTV  VARCHAR2(1) default 'N' not null;
comment on column BTE_PROAPL.TAP_PLNOTV is 'INDICA SI PERMITE PLAZO NOTIFICACIONES VARIABLE (S/N)';

ALTER table BTE_PROAPL MODIFY TAP_URL VARCHAR2(500);