package es.caib.redose.ws.v1.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Jul 23 13:38:33 CEST 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:redose:ws:v1:services", name = "BackofficeFacade")
@XmlSeeAlso({es.caib.redose.ws.v1.model.ObjectFactory.class})
public interface BackofficeFacade {

    @ResponseWrapper(localName = "consultarDocumentoResponse", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade", className = "es.caib.redose.ws.v1.model.ConsultarDocumentoResponse")
    @RequestWrapper(localName = "consultarDocumento", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade", className = "es.caib.redose.ws.v1.model.ConsultarDocumento")
    @WebResult(name = "consultarDocumentoReturn", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
    @WebMethod
    public es.caib.redose.ws.v1.model.DocumentoRDS consultarDocumento(
        @WebParam(name = "referencia", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
        es.caib.redose.ws.v1.model.ReferenciaRDS referencia
    ) throws BackofficeFacadeException;

    @ResponseWrapper(localName = "insertarDocumentoResponse", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade", className = "es.caib.redose.ws.v1.model.InsertarDocumentoResponse")
    @RequestWrapper(localName = "insertarDocumento", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade", className = "es.caib.redose.ws.v1.model.InsertarDocumento")
    @WebResult(name = "insertarDocumentoReturn", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
    @WebMethod
    public es.caib.redose.ws.v1.model.ReferenciaRDS insertarDocumento(
        @WebParam(name = "documento", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
        es.caib.redose.ws.v1.model.DocumentoRDS documento
    ) throws BackofficeFacadeException;
}
