//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.07 at 08:58:37 AM CEST 
//


package es.caib.xml.justificantepago.modelo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caib.xml.justificantepago.modelo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FIRMA_QNAME = new QName("", "FIRMA");
    private final static QName _DUI_QNAME = new QName("", "DUI");
    private final static QName _LOCALIZADOR_QNAME = new QName("", "LOCALIZADOR");
    private final static QName _FECHAPAGO_QNAME = new QName("", "FECHA_PAGO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.xml.justificantepago.modelo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DATOSPAGO }
     * 
     */
    public DATOSPAGO createDATOSPAGO() {
        return new DATOSPAGO();
    }

    /**
     * Create an instance of {@link JUSTIFICANTEPAGO }
     * 
     */
    public JUSTIFICANTEPAGO createJUSTIFICANTEPAGO() {
        return new JUSTIFICANTEPAGO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIRMA")
    public JAXBElement<String> createFIRMA(String value) {
        return new JAXBElement<String>(_FIRMA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DUI")
    public JAXBElement<String> createDUI(String value) {
        return new JAXBElement<String>(_DUI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LOCALIZADOR")
    public JAXBElement<String> createLOCALIZADOR(String value) {
        return new JAXBElement<String>(_LOCALIZADOR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FECHA_PAGO")
    public JAXBElement<String> createFECHAPAGO(String value) {
        return new JAXBElement<String>(_FECHAPAGO_QNAME, String.class, null, value);
    }

}
