-- FIN TRAMITE AUTO PARA TRAMITES CON PAGO FINALIZADO
ALTER table ZPE_TRAPER  ADD TPE_ALTFINA VARCHAR2(1) default 'N' not null;
comment on column ZPE_TRAPER.TPE_ALTFINA is
'INDICA SI SE INTENTA FINALIZAR TRAMITE ANONIMO CUANDO SE GENERA ALERTA DE TRAMITE INACABADO CON PAGO REALIZADO';

ALTER table ZPE_TPEBCK   ADD TPB_ALTFINA VARCHAR2(1) default 'N' not null;
comment on column ZPE_TPEBCK .TPB_ALTFINA is
'INDICA SI SE INTENTA FINALIZAR TRAMITE ANONIMO CUANDO SE GENERA ALERTA DE TRAMITE INACABADO CON PAGO REALIZADO';