package es.caib.redose.model;
// Generated 07-mar-2006 18:19:33 by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * Version generated by hbm2java
 */

public class Version  implements java.io.Serializable {


    // Fields    

     private Long codigo;
     private Modelo modelo;
     private int version;
     private String descripcion;
     private Set plantillas = new HashSet(0);


    // Constructors

    /** default constructor */
    public Version() {
    }

    

   
    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long verCodi) {
        this.codigo = verCodi;
    }

    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo redoseModelo) {
        this.modelo = redoseModelo;
    }

    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int verVersio) {
        this.version = verVersio;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String verDesc) {
        this.descripcion = verDesc;
    }

    public Set getPlantillas() {
        return this.plantillas;
    }
    
    public void setPlantillas(Set redosePlantis) {
        this.plantillas = redosePlantis;
    }
   
    public void addPlantilla(Plantilla plantilla){
    	plantilla.setVersion(this);
    	this.plantillas.add(plantilla);    	
    }
    
    public void removePlantilla(Plantilla plantilla){    	
    	plantillas.remove(plantilla);    	
    }
    
}
