/* ENTRADAS PREREGISTROS */

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
	SELECT NEXTVAL('ZPE_SEQIND'), PRE_NIFRTE, 'P', PRE_CODIGO, 'Número preregistro', PRE_NUMPRE
        FROM  ZPE_PREREG
        WHERE  PRE_NIVAUT <> 'A' AND PRE_NIFRTE IS NOT NULL;

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
	SELECT NEXTVAL('ZPE_SEQIND'), PRE_NIFRTE, 'P', PRE_CODIGO, 'Número registro', PRE_NUMREG
        FROM  ZPE_PREREG
        WHERE  PRE_NIVAUT <> 'A'  AND PRE_NIFRTE IS NOT NULL AND PRE_NUMREG IS NOT NULL;
 
INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
	SELECT NEXTVAL('ZPE_SEQIND'), PRE_NIFRTE, 'P', PRE_CODIGO, 'Título trámite', PRE_DESC
        FROM  ZPE_PREREG
        WHERE  PRE_NIVAUT <> 'A'  AND PRE_NIFRTE IS NOT NULL;

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
	SELECT NEXTVAL('ZPE_SEQIND'), PRE_NIFRTE, 'P', PRE_CODIGO, 'Nif representado', PRE_NIFRDO
        FROM  ZPE_PREREG
        WHERE  PRE_NIVAUT <> 'A' AND PRE_NIFRTE IS NOT NULL AND PRE_NIFRDO IS NOT NULL;

INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR) 
	SELECT NEXTVAL('ZPE_SEQIND'), PRE_NIFRTE, 'P', PRE_CODIGO, 'Nombre representado', PRE_NOMRDO
        FROM  ZPE_PREREG
        WHERE  PRE_NIVAUT <> 'A' AND PRE_NIFRTE IS NOT NULL AND PRE_NOMRDO IS NOT NULL;

				
/* DOCS ENTRADAS PREREGISTROS */
INSERT INTO ZPE_INDELE (IND_CODIGO, IND_NIF, IND_TIPEL, IND_CODEL, IND_DESCR, IND_VALOR)
SELECT NEXTVAL('ZPE_SEQIND'), PRE_NIFRTE, 'P', PRE_CODIGO,  DPR_DOCIDE || '(' || to_char(DPR_DOCNUM, '999') || ')', DPR_DESC
FROM ZPE_DOCPRE, ZPE_PREREG 
WHERE PRE_CODIGO = DPR_CODPRE AND PRE_NIVAUT <> 'A' AND PRE_NIFRTE IS NOT NULL AND DPR_DOCIDE <> 'DTP';
						